/* soapAmazonSearchBindingProxy.h
   Generated by gSOAP 2.7.11 from ../AmazonWebServices.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapAmazonSearchBindingProxy_H
#define soapAmazonSearchBindingProxy_H
#include "soapH.h"
class AmazonSearchBinding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'AmazonSearchBinding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	AmazonSearchBinding()
	{ soap = soap_new(); endpoint = "http://soap.amazon.com/onca/soap2"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://soap.amazon.com", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~AmazonSearchBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'KeywordSearchRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__KeywordSearchRequest(ns1__KeywordRequest *KeywordSearchRequest, struct ns1__KeywordSearchRequestResponse &_param_1) { return soap ? soap_call_ns1__KeywordSearchRequest(soap, endpoint, NULL, KeywordSearchRequest, _param_1) : SOAP_EOM; };
	/// Invoke 'PowerSearchRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__PowerSearchRequest(ns1__PowerRequest *PowerSearchRequest, struct ns1__PowerSearchRequestResponse &_param_2) { return soap ? soap_call_ns1__PowerSearchRequest(soap, endpoint, NULL, PowerSearchRequest, _param_2) : SOAP_EOM; };
	/// Invoke 'BrowseNodeSearchRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__BrowseNodeSearchRequest(ns1__BrowseNodeRequest *BrowseNodeSearchRequest, struct ns1__BrowseNodeSearchRequestResponse &_param_3) { return soap ? soap_call_ns1__BrowseNodeSearchRequest(soap, endpoint, NULL, BrowseNodeSearchRequest, _param_3) : SOAP_EOM; };
	/// Invoke 'AsinSearchRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__AsinSearchRequest(ns1__AsinRequest *AsinSearchRequest, struct ns1__AsinSearchRequestResponse &_param_4) { return soap ? soap_call_ns1__AsinSearchRequest(soap, endpoint, NULL, AsinSearchRequest, _param_4) : SOAP_EOM; };
	/// Invoke 'BlendedSearchRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__BlendedSearchRequest(ns1__BlendedRequest *BlendedSearchRequest, struct ns1__BlendedSearchRequestResponse &_param_5) { return soap ? soap_call_ns1__BlendedSearchRequest(soap, endpoint, NULL, BlendedSearchRequest, _param_5) : SOAP_EOM; };
	/// Invoke 'UpcSearchRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__UpcSearchRequest(ns1__UpcRequest *UpcSearchRequest, struct ns1__UpcSearchRequestResponse &_param_6) { return soap ? soap_call_ns1__UpcSearchRequest(soap, endpoint, NULL, UpcSearchRequest, _param_6) : SOAP_EOM; };
	/// Invoke 'AuthorSearchRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__AuthorSearchRequest(ns1__AuthorRequest *AuthorSearchRequest, struct ns1__AuthorSearchRequestResponse &_param_7) { return soap ? soap_call_ns1__AuthorSearchRequest(soap, endpoint, NULL, AuthorSearchRequest, _param_7) : SOAP_EOM; };
	/// Invoke 'ArtistSearchRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__ArtistSearchRequest(ns1__ArtistRequest *ArtistSearchRequest, struct ns1__ArtistSearchRequestResponse &_param_8) { return soap ? soap_call_ns1__ArtistSearchRequest(soap, endpoint, NULL, ArtistSearchRequest, _param_8) : SOAP_EOM; };
	/// Invoke 'ActorSearchRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__ActorSearchRequest(ns1__ActorRequest *ActorSearchRequest, struct ns1__ActorSearchRequestResponse &_param_9) { return soap ? soap_call_ns1__ActorSearchRequest(soap, endpoint, NULL, ActorSearchRequest, _param_9) : SOAP_EOM; };
	/// Invoke 'ManufacturerSearchRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__ManufacturerSearchRequest(ns1__ManufacturerRequest *ManufacturerSearchRequest, struct ns1__ManufacturerSearchRequestResponse &_param_10) { return soap ? soap_call_ns1__ManufacturerSearchRequest(soap, endpoint, NULL, ManufacturerSearchRequest, _param_10) : SOAP_EOM; };
	/// Invoke 'DirectorSearchRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__DirectorSearchRequest(ns1__DirectorRequest *DirectorSearchRequest, struct ns1__DirectorSearchRequestResponse &_param_11) { return soap ? soap_call_ns1__DirectorSearchRequest(soap, endpoint, NULL, DirectorSearchRequest, _param_11) : SOAP_EOM; };
	/// Invoke 'ExchangeSearchRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__ExchangeSearchRequest(ns1__ExchangeRequest *ExchangeSearchRequest, struct ns1__ExchangeSearchRequestResponse &_param_12) { return soap ? soap_call_ns1__ExchangeSearchRequest(soap, endpoint, NULL, ExchangeSearchRequest, _param_12) : SOAP_EOM; };
	/// Invoke 'ListManiaSearchRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__ListManiaSearchRequest(ns1__ListManiaRequest *ListManiaSearchRequest, struct ns1__ListManiaSearchRequestResponse &_param_13) { return soap ? soap_call_ns1__ListManiaSearchRequest(soap, endpoint, NULL, ListManiaSearchRequest, _param_13) : SOAP_EOM; };
	/// Invoke 'WishlistSearchRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__WishlistSearchRequest(ns1__WishlistRequest *WishlistSearchRequest, struct ns1__WishlistSearchRequestResponse &_param_14) { return soap ? soap_call_ns1__WishlistSearchRequest(soap, endpoint, NULL, WishlistSearchRequest, _param_14) : SOAP_EOM; };
	/// Invoke 'SellerProfileSearchRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__SellerProfileSearchRequest(ns1__SellerProfileRequest *SellerProfileSearchRequest, struct ns1__SellerProfileSearchRequestResponse &_param_15) { return soap ? soap_call_ns1__SellerProfileSearchRequest(soap, endpoint, NULL, SellerProfileSearchRequest, _param_15) : SOAP_EOM; };
	/// Invoke 'SellerSearchRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__SellerSearchRequest(ns1__SellerRequest *SellerSearchRequest, struct ns1__SellerSearchRequestResponse &_param_16) { return soap ? soap_call_ns1__SellerSearchRequest(soap, endpoint, NULL, SellerSearchRequest, _param_16) : SOAP_EOM; };
	/// Invoke 'MarketplaceSearchRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__MarketplaceSearchRequest(ns1__MarketplaceRequest *MarketplaceSearchRequest, struct ns1__MarketplaceSearchRequestResponse &_param_17) { return soap ? soap_call_ns1__MarketplaceSearchRequest(soap, endpoint, NULL, MarketplaceSearchRequest, _param_17) : SOAP_EOM; };
	/// Invoke 'SimilaritySearchRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__SimilaritySearchRequest(ns1__SimilarityRequest *SimilaritySearchRequest, struct ns1__SimilaritySearchRequestResponse &_param_18) { return soap ? soap_call_ns1__SimilaritySearchRequest(soap, endpoint, NULL, SimilaritySearchRequest, _param_18) : SOAP_EOM; };
	/// Invoke 'GetShoppingCartRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__GetShoppingCartRequest_(ns1__GetShoppingCartRequest *GetShoppingCartRequest, struct ns1__GetShoppingCartRequestResponse &_param_19) { return soap ? soap_call_ns1__GetShoppingCartRequest_(soap, endpoint, NULL, GetShoppingCartRequest, _param_19) : SOAP_EOM; };
	/// Invoke 'ClearShoppingCartRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__ClearShoppingCartRequest_(ns1__ClearShoppingCartRequest *ClearShoppingCartRequest, struct ns1__ClearShoppingCartRequestResponse &_param_20) { return soap ? soap_call_ns1__ClearShoppingCartRequest_(soap, endpoint, NULL, ClearShoppingCartRequest, _param_20) : SOAP_EOM; };
	/// Invoke 'AddShoppingCartItemsRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__AddShoppingCartItemsRequest_(ns1__AddShoppingCartItemsRequest *AddShoppingCartItemsRequest, struct ns1__AddShoppingCartItemsRequestResponse &_param_21) { return soap ? soap_call_ns1__AddShoppingCartItemsRequest_(soap, endpoint, NULL, AddShoppingCartItemsRequest, _param_21) : SOAP_EOM; };
	/// Invoke 'RemoveShoppingCartItemsRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__RemoveShoppingCartItemsRequest_(ns1__RemoveShoppingCartItemsRequest *RemoveShoppingCartItemsRequest, struct ns1__RemoveShoppingCartItemsRequestResponse &_param_22) { return soap ? soap_call_ns1__RemoveShoppingCartItemsRequest_(soap, endpoint, NULL, RemoveShoppingCartItemsRequest, _param_22) : SOAP_EOM; };
	/// Invoke 'ModifyShoppingCartItemsRequest' of service 'AmazonSearchBinding' and return error code (or SOAP_OK)
	virtual int ns1__ModifyShoppingCartItemsRequest_(ns1__ModifyShoppingCartItemsRequest *ModifyShoppingCartItemsRequest, struct ns1__ModifyShoppingCartItemsRequestResponse &_param_23) { return soap ? soap_call_ns1__ModifyShoppingCartItemsRequest_(soap, endpoint, NULL, ModifyShoppingCartItemsRequest, _param_23) : SOAP_EOM; };
};
#endif
