/* soapIMobileSoap11BindingProxy.h
   Generated by gSOAP 2.7.11 from ../../IMobile.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapIMobileSoap11BindingProxy_H
#define soapIMobileSoap11BindingProxy_H
#include "soapH.h"
class IMobileSoap11Binding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'IMobileSoap11Binding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	IMobileSoap11Binding()
	{ soap = soap_new(); endpoint = "http://localhost:8080/axis2/services/IMobile"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "http://mobile.kenlo.com/xsd", NULL, NULL},
	{"ns3", "http://mobile.kenlo.com/IMobileSoap11Binding", NULL, NULL},
	{"ns1", "http://mobile.kenlo.com", NULL, NULL},
	{"ns4", "http://mobile.kenlo.com/IMobileSoap12Binding", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~IMobileSoap11Binding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'getProductDetails' of service 'IMobileSoap11Binding' and return error code (or SOAP_OK)
	virtual int __ns3__getProductDetails(_ns1__getProductDetails *ns1__getProductDetails, _ns1__getProductDetailsResponse *ns1__getProductDetailsResponse) { return soap ? soap_call___ns3__getProductDetails(soap, endpoint, NULL, ns1__getProductDetails, ns1__getProductDetailsResponse) : SOAP_EOM; };
	/// Invoke 'getCategoryList' of service 'IMobileSoap11Binding' and return error code (or SOAP_OK)
	virtual int __ns3__getCategoryList(_ns1__getCategoryList *ns1__getCategoryList, _ns1__getCategoryListResponse *ns1__getCategoryListResponse) { return soap ? soap_call___ns3__getCategoryList(soap, endpoint, NULL, ns1__getCategoryList, ns1__getCategoryListResponse) : SOAP_EOM; };
	/// Invoke 'getBusinessList' of service 'IMobileSoap11Binding' and return error code (or SOAP_OK)
	virtual int __ns3__getBusinessList(_ns1__getBusinessList *ns1__getBusinessList, _ns1__getBusinessListResponse *ns1__getBusinessListResponse) { return soap ? soap_call___ns3__getBusinessList(soap, endpoint, NULL, ns1__getBusinessList, ns1__getBusinessListResponse) : SOAP_EOM; };
	/// Invoke 'getProductList' of service 'IMobileSoap11Binding' and return error code (or SOAP_OK)
	virtual int __ns3__getProductList(_ns1__getProductList *ns1__getProductList, _ns1__getProductListResponse *ns1__getProductListResponse) { return soap ? soap_call___ns3__getProductList(soap, endpoint, NULL, ns1__getProductList, ns1__getProductListResponse) : SOAP_EOM; };
	/// Invoke 'getBusinessDetails' of service 'IMobileSoap11Binding' and return error code (or SOAP_OK)
	virtual int __ns3__getBusinessDetails(_ns1__getBusinessDetails *ns1__getBusinessDetails, _ns1__getBusinessDetailsResponse *ns1__getBusinessDetailsResponse) { return soap ? soap_call___ns3__getBusinessDetails(soap, endpoint, NULL, ns1__getBusinessDetails, ns1__getBusinessDetailsResponse) : SOAP_EOM; };
};
#endif
