/* soapClient.cpp
   Generated by gSOAP 2.7.11 from ../AmazonWebServices.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.7.11 2008-07-31 07:50:19 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__KeywordSearchRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__KeywordRequest *KeywordSearchRequest, struct ns1__KeywordSearchRequestResponse &_param_1)
{	struct ns1__KeywordSearchRequest soap_tmp_ns1__KeywordSearchRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__KeywordSearchRequest.KeywordSearchRequest = KeywordSearchRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__KeywordSearchRequest(soap, &soap_tmp_ns1__KeywordSearchRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__KeywordSearchRequest(soap, &soap_tmp_ns1__KeywordSearchRequest, "ns1:KeywordSearchRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__KeywordSearchRequest(soap, &soap_tmp_ns1__KeywordSearchRequest, "ns1:KeywordSearchRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_1)
		return soap_closesock(soap);
	soap_default_ns1__KeywordSearchRequestResponse(soap, &_param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__KeywordSearchRequestResponse(soap, &_param_1, "ns1:KeywordSearchRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__PowerSearchRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__PowerRequest *PowerSearchRequest, struct ns1__PowerSearchRequestResponse &_param_2)
{	struct ns1__PowerSearchRequest soap_tmp_ns1__PowerSearchRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__PowerSearchRequest.PowerSearchRequest = PowerSearchRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__PowerSearchRequest(soap, &soap_tmp_ns1__PowerSearchRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__PowerSearchRequest(soap, &soap_tmp_ns1__PowerSearchRequest, "ns1:PowerSearchRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__PowerSearchRequest(soap, &soap_tmp_ns1__PowerSearchRequest, "ns1:PowerSearchRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_2)
		return soap_closesock(soap);
	soap_default_ns1__PowerSearchRequestResponse(soap, &_param_2);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__PowerSearchRequestResponse(soap, &_param_2, "ns1:PowerSearchRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__BrowseNodeSearchRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__BrowseNodeRequest *BrowseNodeSearchRequest, struct ns1__BrowseNodeSearchRequestResponse &_param_3)
{	struct ns1__BrowseNodeSearchRequest soap_tmp_ns1__BrowseNodeSearchRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__BrowseNodeSearchRequest.BrowseNodeSearchRequest = BrowseNodeSearchRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__BrowseNodeSearchRequest(soap, &soap_tmp_ns1__BrowseNodeSearchRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__BrowseNodeSearchRequest(soap, &soap_tmp_ns1__BrowseNodeSearchRequest, "ns1:BrowseNodeSearchRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__BrowseNodeSearchRequest(soap, &soap_tmp_ns1__BrowseNodeSearchRequest, "ns1:BrowseNodeSearchRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_3)
		return soap_closesock(soap);
	soap_default_ns1__BrowseNodeSearchRequestResponse(soap, &_param_3);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__BrowseNodeSearchRequestResponse(soap, &_param_3, "ns1:BrowseNodeSearchRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__AsinSearchRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__AsinRequest *AsinSearchRequest, struct ns1__AsinSearchRequestResponse &_param_4)
{	struct ns1__AsinSearchRequest soap_tmp_ns1__AsinSearchRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__AsinSearchRequest.AsinSearchRequest = AsinSearchRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__AsinSearchRequest(soap, &soap_tmp_ns1__AsinSearchRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__AsinSearchRequest(soap, &soap_tmp_ns1__AsinSearchRequest, "ns1:AsinSearchRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__AsinSearchRequest(soap, &soap_tmp_ns1__AsinSearchRequest, "ns1:AsinSearchRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_4)
		return soap_closesock(soap);
	soap_default_ns1__AsinSearchRequestResponse(soap, &_param_4);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__AsinSearchRequestResponse(soap, &_param_4, "ns1:AsinSearchRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__BlendedSearchRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__BlendedRequest *BlendedSearchRequest, struct ns1__BlendedSearchRequestResponse &_param_5)
{	struct ns1__BlendedSearchRequest soap_tmp_ns1__BlendedSearchRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__BlendedSearchRequest.BlendedSearchRequest = BlendedSearchRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__BlendedSearchRequest(soap, &soap_tmp_ns1__BlendedSearchRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__BlendedSearchRequest(soap, &soap_tmp_ns1__BlendedSearchRequest, "ns1:BlendedSearchRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__BlendedSearchRequest(soap, &soap_tmp_ns1__BlendedSearchRequest, "ns1:BlendedSearchRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_5)
		return soap_closesock(soap);
	soap_default_ns1__BlendedSearchRequestResponse(soap, &_param_5);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__BlendedSearchRequestResponse(soap, &_param_5, "ns1:BlendedSearchRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__UpcSearchRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__UpcRequest *UpcSearchRequest, struct ns1__UpcSearchRequestResponse &_param_6)
{	struct ns1__UpcSearchRequest soap_tmp_ns1__UpcSearchRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__UpcSearchRequest.UpcSearchRequest = UpcSearchRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__UpcSearchRequest(soap, &soap_tmp_ns1__UpcSearchRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__UpcSearchRequest(soap, &soap_tmp_ns1__UpcSearchRequest, "ns1:UpcSearchRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__UpcSearchRequest(soap, &soap_tmp_ns1__UpcSearchRequest, "ns1:UpcSearchRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_6)
		return soap_closesock(soap);
	soap_default_ns1__UpcSearchRequestResponse(soap, &_param_6);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__UpcSearchRequestResponse(soap, &_param_6, "ns1:UpcSearchRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__AuthorSearchRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__AuthorRequest *AuthorSearchRequest, struct ns1__AuthorSearchRequestResponse &_param_7)
{	struct ns1__AuthorSearchRequest soap_tmp_ns1__AuthorSearchRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__AuthorSearchRequest.AuthorSearchRequest = AuthorSearchRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__AuthorSearchRequest(soap, &soap_tmp_ns1__AuthorSearchRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__AuthorSearchRequest(soap, &soap_tmp_ns1__AuthorSearchRequest, "ns1:AuthorSearchRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__AuthorSearchRequest(soap, &soap_tmp_ns1__AuthorSearchRequest, "ns1:AuthorSearchRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_7)
		return soap_closesock(soap);
	soap_default_ns1__AuthorSearchRequestResponse(soap, &_param_7);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__AuthorSearchRequestResponse(soap, &_param_7, "ns1:AuthorSearchRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ArtistSearchRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__ArtistRequest *ArtistSearchRequest, struct ns1__ArtistSearchRequestResponse &_param_8)
{	struct ns1__ArtistSearchRequest soap_tmp_ns1__ArtistSearchRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__ArtistSearchRequest.ArtistSearchRequest = ArtistSearchRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__ArtistSearchRequest(soap, &soap_tmp_ns1__ArtistSearchRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ArtistSearchRequest(soap, &soap_tmp_ns1__ArtistSearchRequest, "ns1:ArtistSearchRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ArtistSearchRequest(soap, &soap_tmp_ns1__ArtistSearchRequest, "ns1:ArtistSearchRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_8)
		return soap_closesock(soap);
	soap_default_ns1__ArtistSearchRequestResponse(soap, &_param_8);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__ArtistSearchRequestResponse(soap, &_param_8, "ns1:ArtistSearchRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ActorSearchRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__ActorRequest *ActorSearchRequest, struct ns1__ActorSearchRequestResponse &_param_9)
{	struct ns1__ActorSearchRequest soap_tmp_ns1__ActorSearchRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__ActorSearchRequest.ActorSearchRequest = ActorSearchRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__ActorSearchRequest(soap, &soap_tmp_ns1__ActorSearchRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ActorSearchRequest(soap, &soap_tmp_ns1__ActorSearchRequest, "ns1:ActorSearchRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ActorSearchRequest(soap, &soap_tmp_ns1__ActorSearchRequest, "ns1:ActorSearchRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_9)
		return soap_closesock(soap);
	soap_default_ns1__ActorSearchRequestResponse(soap, &_param_9);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__ActorSearchRequestResponse(soap, &_param_9, "ns1:ActorSearchRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ManufacturerSearchRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__ManufacturerRequest *ManufacturerSearchRequest, struct ns1__ManufacturerSearchRequestResponse &_param_10)
{	struct ns1__ManufacturerSearchRequest soap_tmp_ns1__ManufacturerSearchRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__ManufacturerSearchRequest.ManufacturerSearchRequest = ManufacturerSearchRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__ManufacturerSearchRequest(soap, &soap_tmp_ns1__ManufacturerSearchRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ManufacturerSearchRequest(soap, &soap_tmp_ns1__ManufacturerSearchRequest, "ns1:ManufacturerSearchRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ManufacturerSearchRequest(soap, &soap_tmp_ns1__ManufacturerSearchRequest, "ns1:ManufacturerSearchRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_10)
		return soap_closesock(soap);
	soap_default_ns1__ManufacturerSearchRequestResponse(soap, &_param_10);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__ManufacturerSearchRequestResponse(soap, &_param_10, "ns1:ManufacturerSearchRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__DirectorSearchRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__DirectorRequest *DirectorSearchRequest, struct ns1__DirectorSearchRequestResponse &_param_11)
{	struct ns1__DirectorSearchRequest soap_tmp_ns1__DirectorSearchRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__DirectorSearchRequest.DirectorSearchRequest = DirectorSearchRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__DirectorSearchRequest(soap, &soap_tmp_ns1__DirectorSearchRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__DirectorSearchRequest(soap, &soap_tmp_ns1__DirectorSearchRequest, "ns1:DirectorSearchRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__DirectorSearchRequest(soap, &soap_tmp_ns1__DirectorSearchRequest, "ns1:DirectorSearchRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_11)
		return soap_closesock(soap);
	soap_default_ns1__DirectorSearchRequestResponse(soap, &_param_11);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__DirectorSearchRequestResponse(soap, &_param_11, "ns1:DirectorSearchRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ExchangeSearchRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__ExchangeRequest *ExchangeSearchRequest, struct ns1__ExchangeSearchRequestResponse &_param_12)
{	struct ns1__ExchangeSearchRequest soap_tmp_ns1__ExchangeSearchRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__ExchangeSearchRequest.ExchangeSearchRequest = ExchangeSearchRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__ExchangeSearchRequest(soap, &soap_tmp_ns1__ExchangeSearchRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ExchangeSearchRequest(soap, &soap_tmp_ns1__ExchangeSearchRequest, "ns1:ExchangeSearchRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ExchangeSearchRequest(soap, &soap_tmp_ns1__ExchangeSearchRequest, "ns1:ExchangeSearchRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_12)
		return soap_closesock(soap);
	soap_default_ns1__ExchangeSearchRequestResponse(soap, &_param_12);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__ExchangeSearchRequestResponse(soap, &_param_12, "ns1:ExchangeSearchRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ListManiaSearchRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__ListManiaRequest *ListManiaSearchRequest, struct ns1__ListManiaSearchRequestResponse &_param_13)
{	struct ns1__ListManiaSearchRequest soap_tmp_ns1__ListManiaSearchRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__ListManiaSearchRequest.ListManiaSearchRequest = ListManiaSearchRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__ListManiaSearchRequest(soap, &soap_tmp_ns1__ListManiaSearchRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ListManiaSearchRequest(soap, &soap_tmp_ns1__ListManiaSearchRequest, "ns1:ListManiaSearchRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ListManiaSearchRequest(soap, &soap_tmp_ns1__ListManiaSearchRequest, "ns1:ListManiaSearchRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_13)
		return soap_closesock(soap);
	soap_default_ns1__ListManiaSearchRequestResponse(soap, &_param_13);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__ListManiaSearchRequestResponse(soap, &_param_13, "ns1:ListManiaSearchRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__WishlistSearchRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__WishlistRequest *WishlistSearchRequest, struct ns1__WishlistSearchRequestResponse &_param_14)
{	struct ns1__WishlistSearchRequest soap_tmp_ns1__WishlistSearchRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__WishlistSearchRequest.WishlistSearchRequest = WishlistSearchRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__WishlistSearchRequest(soap, &soap_tmp_ns1__WishlistSearchRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__WishlistSearchRequest(soap, &soap_tmp_ns1__WishlistSearchRequest, "ns1:WishlistSearchRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__WishlistSearchRequest(soap, &soap_tmp_ns1__WishlistSearchRequest, "ns1:WishlistSearchRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_14)
		return soap_closesock(soap);
	soap_default_ns1__WishlistSearchRequestResponse(soap, &_param_14);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__WishlistSearchRequestResponse(soap, &_param_14, "ns1:WishlistSearchRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__SellerProfileSearchRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__SellerProfileRequest *SellerProfileSearchRequest, struct ns1__SellerProfileSearchRequestResponse &_param_15)
{	struct ns1__SellerProfileSearchRequest soap_tmp_ns1__SellerProfileSearchRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__SellerProfileSearchRequest.SellerProfileSearchRequest = SellerProfileSearchRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__SellerProfileSearchRequest(soap, &soap_tmp_ns1__SellerProfileSearchRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SellerProfileSearchRequest(soap, &soap_tmp_ns1__SellerProfileSearchRequest, "ns1:SellerProfileSearchRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SellerProfileSearchRequest(soap, &soap_tmp_ns1__SellerProfileSearchRequest, "ns1:SellerProfileSearchRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_15)
		return soap_closesock(soap);
	soap_default_ns1__SellerProfileSearchRequestResponse(soap, &_param_15);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SellerProfileSearchRequestResponse(soap, &_param_15, "ns1:SellerProfileSearchRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__SellerSearchRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__SellerRequest *SellerSearchRequest, struct ns1__SellerSearchRequestResponse &_param_16)
{	struct ns1__SellerSearchRequest soap_tmp_ns1__SellerSearchRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__SellerSearchRequest.SellerSearchRequest = SellerSearchRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__SellerSearchRequest(soap, &soap_tmp_ns1__SellerSearchRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SellerSearchRequest(soap, &soap_tmp_ns1__SellerSearchRequest, "ns1:SellerSearchRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SellerSearchRequest(soap, &soap_tmp_ns1__SellerSearchRequest, "ns1:SellerSearchRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_16)
		return soap_closesock(soap);
	soap_default_ns1__SellerSearchRequestResponse(soap, &_param_16);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SellerSearchRequestResponse(soap, &_param_16, "ns1:SellerSearchRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__MarketplaceSearchRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__MarketplaceRequest *MarketplaceSearchRequest, struct ns1__MarketplaceSearchRequestResponse &_param_17)
{	struct ns1__MarketplaceSearchRequest soap_tmp_ns1__MarketplaceSearchRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__MarketplaceSearchRequest.MarketplaceSearchRequest = MarketplaceSearchRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__MarketplaceSearchRequest(soap, &soap_tmp_ns1__MarketplaceSearchRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__MarketplaceSearchRequest(soap, &soap_tmp_ns1__MarketplaceSearchRequest, "ns1:MarketplaceSearchRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__MarketplaceSearchRequest(soap, &soap_tmp_ns1__MarketplaceSearchRequest, "ns1:MarketplaceSearchRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_17)
		return soap_closesock(soap);
	soap_default_ns1__MarketplaceSearchRequestResponse(soap, &_param_17);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__MarketplaceSearchRequestResponse(soap, &_param_17, "ns1:MarketplaceSearchRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__SimilaritySearchRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__SimilarityRequest *SimilaritySearchRequest, struct ns1__SimilaritySearchRequestResponse &_param_18)
{	struct ns1__SimilaritySearchRequest soap_tmp_ns1__SimilaritySearchRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__SimilaritySearchRequest.SimilaritySearchRequest = SimilaritySearchRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__SimilaritySearchRequest(soap, &soap_tmp_ns1__SimilaritySearchRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SimilaritySearchRequest(soap, &soap_tmp_ns1__SimilaritySearchRequest, "ns1:SimilaritySearchRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SimilaritySearchRequest(soap, &soap_tmp_ns1__SimilaritySearchRequest, "ns1:SimilaritySearchRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_18)
		return soap_closesock(soap);
	soap_default_ns1__SimilaritySearchRequestResponse(soap, &_param_18);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__SimilaritySearchRequestResponse(soap, &_param_18, "ns1:SimilaritySearchRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__GetShoppingCartRequest_(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__GetShoppingCartRequest *GetShoppingCartRequest, struct ns1__GetShoppingCartRequestResponse &_param_19)
{	struct ns1__GetShoppingCartRequest_ soap_tmp_ns1__GetShoppingCartRequest_;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__GetShoppingCartRequest_.GetShoppingCartRequest = GetShoppingCartRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__GetShoppingCartRequest_(soap, &soap_tmp_ns1__GetShoppingCartRequest_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__GetShoppingCartRequest_(soap, &soap_tmp_ns1__GetShoppingCartRequest_, "ns1:GetShoppingCartRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__GetShoppingCartRequest_(soap, &soap_tmp_ns1__GetShoppingCartRequest_, "ns1:GetShoppingCartRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_19)
		return soap_closesock(soap);
	soap_default_ns1__GetShoppingCartRequestResponse(soap, &_param_19);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__GetShoppingCartRequestResponse(soap, &_param_19, "ns1:GetShoppingCartRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ClearShoppingCartRequest_(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__ClearShoppingCartRequest *ClearShoppingCartRequest, struct ns1__ClearShoppingCartRequestResponse &_param_20)
{	struct ns1__ClearShoppingCartRequest_ soap_tmp_ns1__ClearShoppingCartRequest_;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__ClearShoppingCartRequest_.ClearShoppingCartRequest = ClearShoppingCartRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__ClearShoppingCartRequest_(soap, &soap_tmp_ns1__ClearShoppingCartRequest_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ClearShoppingCartRequest_(soap, &soap_tmp_ns1__ClearShoppingCartRequest_, "ns1:ClearShoppingCartRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ClearShoppingCartRequest_(soap, &soap_tmp_ns1__ClearShoppingCartRequest_, "ns1:ClearShoppingCartRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_20)
		return soap_closesock(soap);
	soap_default_ns1__ClearShoppingCartRequestResponse(soap, &_param_20);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__ClearShoppingCartRequestResponse(soap, &_param_20, "ns1:ClearShoppingCartRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__AddShoppingCartItemsRequest_(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__AddShoppingCartItemsRequest *AddShoppingCartItemsRequest, struct ns1__AddShoppingCartItemsRequestResponse &_param_21)
{	struct ns1__AddShoppingCartItemsRequest_ soap_tmp_ns1__AddShoppingCartItemsRequest_;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__AddShoppingCartItemsRequest_.AddShoppingCartItemsRequest = AddShoppingCartItemsRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__AddShoppingCartItemsRequest_(soap, &soap_tmp_ns1__AddShoppingCartItemsRequest_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__AddShoppingCartItemsRequest_(soap, &soap_tmp_ns1__AddShoppingCartItemsRequest_, "ns1:AddShoppingCartItemsRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__AddShoppingCartItemsRequest_(soap, &soap_tmp_ns1__AddShoppingCartItemsRequest_, "ns1:AddShoppingCartItemsRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_21)
		return soap_closesock(soap);
	soap_default_ns1__AddShoppingCartItemsRequestResponse(soap, &_param_21);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__AddShoppingCartItemsRequestResponse(soap, &_param_21, "ns1:AddShoppingCartItemsRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__RemoveShoppingCartItemsRequest_(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__RemoveShoppingCartItemsRequest *RemoveShoppingCartItemsRequest, struct ns1__RemoveShoppingCartItemsRequestResponse &_param_22)
{	struct ns1__RemoveShoppingCartItemsRequest_ soap_tmp_ns1__RemoveShoppingCartItemsRequest_;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__RemoveShoppingCartItemsRequest_.RemoveShoppingCartItemsRequest = RemoveShoppingCartItemsRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__RemoveShoppingCartItemsRequest_(soap, &soap_tmp_ns1__RemoveShoppingCartItemsRequest_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__RemoveShoppingCartItemsRequest_(soap, &soap_tmp_ns1__RemoveShoppingCartItemsRequest_, "ns1:RemoveShoppingCartItemsRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__RemoveShoppingCartItemsRequest_(soap, &soap_tmp_ns1__RemoveShoppingCartItemsRequest_, "ns1:RemoveShoppingCartItemsRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_22)
		return soap_closesock(soap);
	soap_default_ns1__RemoveShoppingCartItemsRequestResponse(soap, &_param_22);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__RemoveShoppingCartItemsRequestResponse(soap, &_param_22, "ns1:RemoveShoppingCartItemsRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ModifyShoppingCartItemsRequest_(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__ModifyShoppingCartItemsRequest *ModifyShoppingCartItemsRequest, struct ns1__ModifyShoppingCartItemsRequestResponse &_param_23)
{	struct ns1__ModifyShoppingCartItemsRequest_ soap_tmp_ns1__ModifyShoppingCartItemsRequest_;
	if (!soap_endpoint)
		soap_endpoint = "http://soap.amazon.com/onca/soap2";
	if (!soap_action)
		soap_action = "http://soap.amazon.com";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__ModifyShoppingCartItemsRequest_.ModifyShoppingCartItemsRequest = ModifyShoppingCartItemsRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__ModifyShoppingCartItemsRequest_(soap, &soap_tmp_ns1__ModifyShoppingCartItemsRequest_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ModifyShoppingCartItemsRequest_(soap, &soap_tmp_ns1__ModifyShoppingCartItemsRequest_, "ns1:ModifyShoppingCartItemsRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ModifyShoppingCartItemsRequest_(soap, &soap_tmp_ns1__ModifyShoppingCartItemsRequest_, "ns1:ModifyShoppingCartItemsRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_23)
		return soap_closesock(soap);
	soap_default_ns1__ModifyShoppingCartItemsRequestResponse(soap, &_param_23);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__ModifyShoppingCartItemsRequestResponse(soap, &_param_23, "ns1:ModifyShoppingCartItemsRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

/* End of soapClient.cpp */
