/* soapMobileServiceSoap11BindingProxy.h
   Generated by gSOAP 2.7.11 from MobileService.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapMobileServiceSoap11BindingProxy_H
#define soapMobileServiceSoap11BindingProxy_H
#include "soapH.h"
class MobileServiceSoap11Binding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'MobileServiceSoap11Binding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	MobileServiceSoap11Binding()
	{ soap = soap_new(); endpoint = "http://kenlo.gotdns.com:8080/axis2/services/MobileService.MobileServiceHttpSoap11Endpoint"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns3", "http://mobile.kenlo.com/MobileServiceSoap11Binding", NULL, NULL},
	{"ns2", "http://mobile.kenlo.com/xsd", NULL, NULL},
	{"ns4", "http://mobile.kenlo.com/MobileServiceSoap12Binding", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~MobileServiceSoap11Binding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'getCategory' of service 'MobileServiceSoap11Binding' and return error code (or SOAP_OK)
	virtual int __ns3__getCategory(_ns2__getCategory *ns2__getCategory, _ns2__getCategoryResponse *ns2__getCategoryResponse) { return soap ? soap_call___ns3__getCategory(soap, endpoint, NULL, ns2__getCategory, ns2__getCategoryResponse) : SOAP_EOM; };
	/// Invoke 'getProductDetails' of service 'MobileServiceSoap11Binding' and return error code (or SOAP_OK)
	virtual int __ns3__getProductDetails(_ns2__getProductDetails *ns2__getProductDetails, _ns2__getProductDetailsResponse *ns2__getProductDetailsResponse) { return soap ? soap_call___ns3__getProductDetails(soap, endpoint, NULL, ns2__getProductDetails, ns2__getProductDetailsResponse) : SOAP_EOM; };
	/// Invoke 'getPopularItems' of service 'MobileServiceSoap11Binding' and return error code (or SOAP_OK)
	virtual int __ns3__getPopularItems(_ns2__getPopularItems *ns2__getPopularItems, _ns2__getPopularItemsResponse *ns2__getPopularItemsResponse) { return soap ? soap_call___ns3__getPopularItems(soap, endpoint, NULL, ns2__getPopularItems, ns2__getPopularItemsResponse) : SOAP_EOM; };
	/// Invoke 'getCategoryList' of service 'MobileServiceSoap11Binding' and return error code (or SOAP_OK)
	virtual int __ns3__getCategoryList(_ns2__getCategoryList *ns2__getCategoryList, _ns2__getCategoryListResponse *ns2__getCategoryListResponse) { return soap ? soap_call___ns3__getCategoryList(soap, endpoint, NULL, ns2__getCategoryList, ns2__getCategoryListResponse) : SOAP_EOM; };
	/// Invoke 'getBusinessList' of service 'MobileServiceSoap11Binding' and return error code (or SOAP_OK)
	virtual int __ns3__getBusinessList(_ns2__getBusinessList *ns2__getBusinessList, _ns2__getBusinessListResponse *ns2__getBusinessListResponse) { return soap ? soap_call___ns3__getBusinessList(soap, endpoint, NULL, ns2__getBusinessList, ns2__getBusinessListResponse) : SOAP_EOM; };
	/// Invoke 'getProductList' of service 'MobileServiceSoap11Binding' and return error code (or SOAP_OK)
	virtual int __ns3__getProductList(_ns2__getProductList *ns2__getProductList, _ns2__getProductListResponse *ns2__getProductListResponse) { return soap ? soap_call___ns3__getProductList(soap, endpoint, NULL, ns2__getProductList, ns2__getProductListResponse) : SOAP_EOM; };
	/// Invoke 'getBusinessDetails' of service 'MobileServiceSoap11Binding' and return error code (or SOAP_OK)
	virtual int __ns3__getBusinessDetails(_ns2__getBusinessDetails *ns2__getBusinessDetails, _ns2__getBusinessDetailsResponse *ns2__getBusinessDetailsResponse) { return soap ? soap_call___ns3__getBusinessDetails(soap, endpoint, NULL, ns2__getBusinessDetails, ns2__getBusinessDetailsResponse) : SOAP_EOM; };
};
#endif
