/* soapStub.h
   Generated by gSOAP 2.7.11 from ../../mobile.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include <vector>
#include "stdsoap2.h"

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not redeclare here */

#endif

#ifndef SOAP_TYPE_xsd__anyType
#define SOAP_TYPE_xsd__anyType (8)
/* Primitive xsd:anyType schema type: */
class SOAP_CMAC xsd__anyType
{
public:
	char *__item;
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 8; } /* = unique id SOAP_TYPE_xsd__anyType */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         xsd__anyType() : __item(NULL), soap(NULL) { }
	virtual ~xsd__anyType() { }
};
#endif

#ifndef SOAP_TYPE_xsd__float
#define SOAP_TYPE_xsd__float (10)
/* Primitive xsd:float schema type: */
class SOAP_CMAC xsd__float : public xsd__anyType
{
public:
	float __item;
public:
	virtual int soap_type() const { return 10; } /* = unique id SOAP_TYPE_xsd__float */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         xsd__float() : __item(0) { }
	virtual ~xsd__float() { }
};
#endif

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (12)
/* Primitive xsd:int schema type: */
class SOAP_CMAC xsd__int : public xsd__anyType
{
public:
	int __item;
public:
	virtual int soap_type() const { return 12; } /* = unique id SOAP_TYPE_xsd__int */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         xsd__int() : __item(0) { }
	virtual ~xsd__int() { }
};
#endif

#if 0 /* volatile type: do not redeclare here */

#endif

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (13)
/* Primitive xsd:string schema type: */
class SOAP_CMAC xsd__string : public xsd__anyType
{
public:
	std::string __item;
public:
	virtual int soap_type() const { return 13; } /* = unique id SOAP_TYPE_xsd__string */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         xsd__string()  { }
	virtual ~xsd__string() { }
};
#endif

#ifndef SOAP_TYPE_ns2__MItem
#define SOAP_TYPE_ns2__MItem (15)
/* ns2:MItem */
class SOAP_CMAC ns2__MItem : public xsd__anyType
{
public:
	std::string *highlight1;	/* optional element of type xsd:string */
	std::string *highlight2;	/* optional element of type xsd:string */
	int *id;	/* optional element of type xsd:int */
	std::string *imageURL;	/* optional element of type xsd:string */
	std::string *name;	/* optional element of type xsd:string */
public:
	virtual int soap_type() const { return 15; } /* = unique id SOAP_TYPE_ns2__MItem */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns2__MItem() : highlight1(NULL), highlight2(NULL), id(NULL), imageURL(NULL), name(NULL) { }
	virtual ~ns2__MItem() { }
};
#endif

#ifndef SOAP_TYPE_ns2__MCategory
#define SOAP_TYPE_ns2__MCategory (17)
/* ns2:MCategory */
class SOAP_CMAC ns2__MCategory : public xsd__anyType
{
public:
	std::vector<ns2__MCategory * >childCategories;	/* optional element of type ns2:MCategory */
	int *id;	/* optional element of type xsd:int */
	std::string *imageURL;	/* optional element of type xsd:string */
	std::string *name;	/* optional element of type xsd:string */
	int *orderId;	/* optional element of type xsd:int */
	int *totalItems;	/* optional element of type xsd:int */
	int *type;	/* optional element of type xsd:int */
public:
	virtual int soap_type() const { return 17; } /* = unique id SOAP_TYPE_ns2__MCategory */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns2__MCategory() : id(NULL), imageURL(NULL), name(NULL), orderId(NULL), totalItems(NULL), type(NULL) { }
	virtual ~ns2__MCategory() { }
};
#endif

#ifndef SOAP_TYPE_ns2__MAddress
#define SOAP_TYPE_ns2__MAddress (20)
/* ns2:MAddress */
class SOAP_CMAC ns2__MAddress : public xsd__anyType
{
public:
	std::string *area;	/* optional element of type xsd:string */
	std::string *city;	/* optional element of type xsd:string */
	std::string *street;	/* optional element of type xsd:string */
	std::string *zipCode;	/* optional element of type xsd:string */
public:
	virtual int soap_type() const { return 20; } /* = unique id SOAP_TYPE_ns2__MAddress */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns2__MAddress() : area(NULL), city(NULL), street(NULL), zipCode(NULL) { }
	virtual ~ns2__MAddress() { }
};
#endif

#ifndef SOAP_TYPE_ns2__MContactInfo
#define SOAP_TYPE_ns2__MContactInfo (21)
/* ns2:MContactInfo */
class SOAP_CMAC ns2__MContactInfo : public xsd__anyType
{
public:
	std::string *contactPerson;	/* optional element of type xsd:string */
	std::string *email;	/* optional element of type xsd:string */
	std::string *fax;	/* optional element of type xsd:string */
	std::string *mobile;	/* optional element of type xsd:string */
	std::string *phone;	/* optional element of type xsd:string */
	std::string *website;	/* optional element of type xsd:string */
public:
	virtual int soap_type() const { return 21; } /* = unique id SOAP_TYPE_ns2__MContactInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns2__MContactInfo() : contactPerson(NULL), email(NULL), fax(NULL), mobile(NULL), phone(NULL), website(NULL) { }
	virtual ~ns2__MContactInfo() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getBusinessList
#define SOAP_TYPE__ns1__getBusinessList (24)
/* ns1:getBusinessList */
class SOAP_CMAC _ns1__getBusinessList
{
public:
	int *param0;	/* optional element of type xsd:int */
	int *param1;	/* optional element of type xsd:int */
	int *param2;	/* optional element of type xsd:int */
	int *param3;	/* optional element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 24; } /* = unique id SOAP_TYPE__ns1__getBusinessList */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getBusinessList() : param0(NULL), param1(NULL), param2(NULL), param3(NULL), soap(NULL) { }
	virtual ~_ns1__getBusinessList() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getBusinessListResponse
#define SOAP_TYPE__ns1__getBusinessListResponse (25)
/* ns1:getBusinessListResponse */
class SOAP_CMAC _ns1__getBusinessListResponse
{
public:
	std::vector<class ns2__MBusinessCard * >return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:MBusinessCard */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 25; } /* = unique id SOAP_TYPE__ns1__getBusinessListResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getBusinessListResponse() : soap(NULL) { }
	virtual ~_ns1__getBusinessListResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getCategoryList
#define SOAP_TYPE__ns1__getCategoryList (26)
/* ns1:getCategoryList */
class SOAP_CMAC _ns1__getCategoryList
{
public:
	int *param0;	/* optional element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 26; } /* = unique id SOAP_TYPE__ns1__getCategoryList */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getCategoryList() : param0(NULL), soap(NULL) { }
	virtual ~_ns1__getCategoryList() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getCategoryListResponse
#define SOAP_TYPE__ns1__getCategoryListResponse (27)
/* ns1:getCategoryListResponse */
class SOAP_CMAC _ns1__getCategoryListResponse
{
public:
	std::vector<ns2__MCategory * >return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:MCategory */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 27; } /* = unique id SOAP_TYPE__ns1__getCategoryListResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getCategoryListResponse() : soap(NULL) { }
	virtual ~_ns1__getCategoryListResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getBusinessDetails
#define SOAP_TYPE__ns1__getBusinessDetails (28)
/* ns1:getBusinessDetails */
class SOAP_CMAC _ns1__getBusinessDetails
{
public:
	int *param0;	/* optional element of type xsd:int */
	int *param1;	/* optional element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 28; } /* = unique id SOAP_TYPE__ns1__getBusinessDetails */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getBusinessDetails() : param0(NULL), param1(NULL), soap(NULL) { }
	virtual ~_ns1__getBusinessDetails() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getBusinessDetailsResponse
#define SOAP_TYPE__ns1__getBusinessDetailsResponse (29)
/* ns1:getBusinessDetailsResponse */
class SOAP_CMAC _ns1__getBusinessDetailsResponse
{
public:
	class ns2__MDetailedBusinessCard *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:MDetailedBusinessCard */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 29; } /* = unique id SOAP_TYPE__ns1__getBusinessDetailsResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getBusinessDetailsResponse() : return_(NULL), soap(NULL) { }
	virtual ~_ns1__getBusinessDetailsResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getProductDetails
#define SOAP_TYPE__ns1__getProductDetails (30)
/* ns1:getProductDetails */
class SOAP_CMAC _ns1__getProductDetails
{
public:
	int *param0;	/* optional element of type xsd:int */
	int *param1;	/* optional element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 30; } /* = unique id SOAP_TYPE__ns1__getProductDetails */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getProductDetails() : param0(NULL), param1(NULL), soap(NULL) { }
	virtual ~_ns1__getProductDetails() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getProductDetailsResponse
#define SOAP_TYPE__ns1__getProductDetailsResponse (31)
/* ns1:getProductDetailsResponse */
class SOAP_CMAC _ns1__getProductDetailsResponse
{
public:
	class ns2__MDetailedProduct *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:MDetailedProduct */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 31; } /* = unique id SOAP_TYPE__ns1__getProductDetailsResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getProductDetailsResponse() : return_(NULL), soap(NULL) { }
	virtual ~_ns1__getProductDetailsResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getProductList
#define SOAP_TYPE__ns1__getProductList (32)
/* ns1:getProductList */
class SOAP_CMAC _ns1__getProductList
{
public:
	int *param0;	/* optional element of type xsd:int */
	int *param1;	/* optional element of type xsd:int */
	int *param2;	/* optional element of type xsd:int */
	int *param3;	/* optional element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 32; } /* = unique id SOAP_TYPE__ns1__getProductList */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getProductList() : param0(NULL), param1(NULL), param2(NULL), param3(NULL), soap(NULL) { }
	virtual ~_ns1__getProductList() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getProductListResponse
#define SOAP_TYPE__ns1__getProductListResponse (33)
/* ns1:getProductListResponse */
class SOAP_CMAC _ns1__getProductListResponse
{
public:
	std::vector<class ns2__MProduct * >return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns2:MProduct */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 33; } /* = unique id SOAP_TYPE__ns1__getProductListResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getProductListResponse() : soap(NULL) { }
	virtual ~_ns1__getProductListResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__helloResponse
#define SOAP_TYPE__ns1__helloResponse (34)
/* ns1:helloResponse */
class SOAP_CMAC _ns1__helloResponse
{
public:
	std::string *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 34; } /* = unique id SOAP_TYPE__ns1__helloResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__helloResponse() : return_(NULL), soap(NULL) { }
	virtual ~_ns1__helloResponse() { }
};
#endif

#ifndef SOAP_TYPE_ns2__MBusinessCard
#define SOAP_TYPE_ns2__MBusinessCard (16)
/* ns2:MBusinessCard */
class SOAP_CMAC ns2__MBusinessCard : public ns2__MItem
{
public:
	int *vipLevel;	/* optional element of type xsd:int */
public:
	virtual int soap_type() const { return 16; } /* = unique id SOAP_TYPE_ns2__MBusinessCard */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns2__MBusinessCard() : vipLevel(NULL) { }
	virtual ~ns2__MBusinessCard() { }
};
#endif

#ifndef SOAP_TYPE_ns2__MDetailedItem
#define SOAP_TYPE_ns2__MDetailedItem (18)
/* ns2:MDetailedItem */
class SOAP_CMAC ns2__MDetailedItem : public ns2__MItem
{
public:
	std::string *details;	/* optional element of type xsd:string */
	std::vector<std::string >galleryImageUrls;	/* optional element of type xsd:string */
	float *rating;	/* optional element of type xsd:float */
	std::string *videoURL;	/* optional element of type xsd:string */
public:
	virtual int soap_type() const { return 18; } /* = unique id SOAP_TYPE_ns2__MDetailedItem */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns2__MDetailedItem() : details(NULL), rating(NULL), videoURL(NULL) { }
	virtual ~ns2__MDetailedItem() { }
};
#endif

#ifndef SOAP_TYPE_ns2__MProduct
#define SOAP_TYPE_ns2__MProduct (23)
/* ns2:MProduct */
class SOAP_CMAC ns2__MProduct : public ns2__MItem
{
public:
	int *stores;	/* optional element of type xsd:int */
public:
	virtual int soap_type() const { return 23; } /* = unique id SOAP_TYPE_ns2__MProduct */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns2__MProduct() : stores(NULL) { }
	virtual ~ns2__MProduct() { }
};
#endif

#ifndef SOAP_TYPE_ns2__MDetailedBusinessCard
#define SOAP_TYPE_ns2__MDetailedBusinessCard (19)
/* ns2:MDetailedBusinessCard */
class SOAP_CMAC ns2__MDetailedBusinessCard : public ns2__MDetailedItem
{
public:
	ns2__MAddress *address;	/* optional element of type ns2:MAddress */
	ns2__MContactInfo *contact;	/* optional element of type ns2:MContactInfo */
	int *vipLevel;	/* optional element of type xsd:int */
public:
	virtual int soap_type() const { return 19; } /* = unique id SOAP_TYPE_ns2__MDetailedBusinessCard */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns2__MDetailedBusinessCard() : address(NULL), contact(NULL), vipLevel(NULL) { }
	virtual ~ns2__MDetailedBusinessCard() { }
};
#endif

#ifndef SOAP_TYPE_ns2__MDetailedProduct
#define SOAP_TYPE_ns2__MDetailedProduct (22)
/* ns2:MDetailedProduct */
class SOAP_CMAC ns2__MDetailedProduct : public ns2__MDetailedItem
{
public:
	std::string *amazonURL;	/* optional element of type xsd:string */
	xsd__anyType *offers;	/* optional element of type xsd:anyType */
	std::string *reviewURL;	/* optional element of type xsd:string */
	int *stores;	/* optional element of type xsd:int */
public:
	virtual int soap_type() const { return 22; } /* = unique id SOAP_TYPE_ns2__MDetailedProduct */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns2__MDetailedProduct() : amazonURL(NULL), offers(NULL), reviewURL(NULL), stores(NULL) { }
	virtual ~ns2__MDetailedProduct() { }
};
#endif

#ifndef SOAP_TYPE___ns3__getProductDetails
#define SOAP_TYPE___ns3__getProductDetails (53)
/* Operation wrapper: */
struct __ns3__getProductDetails
{
public:
	_ns1__getProductDetails *ns1__getProductDetails;	/* optional element of type ns1:getProductDetails */
};
#endif

#ifndef SOAP_TYPE___ns3__hello
#define SOAP_TYPE___ns3__hello (56)
/* Operation wrapper: */
struct __ns3__hello
{
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE___ns3__getCategoryList
#define SOAP_TYPE___ns3__getCategoryList (60)
/* Operation wrapper: */
struct __ns3__getCategoryList
{
public:
	_ns1__getCategoryList *ns1__getCategoryList;	/* optional element of type ns1:getCategoryList */
};
#endif

#ifndef SOAP_TYPE___ns3__getBusinessList
#define SOAP_TYPE___ns3__getBusinessList (64)
/* Operation wrapper: */
struct __ns3__getBusinessList
{
public:
	_ns1__getBusinessList *ns1__getBusinessList;	/* optional element of type ns1:getBusinessList */
};
#endif

#ifndef SOAP_TYPE___ns3__getProductList
#define SOAP_TYPE___ns3__getProductList (68)
/* Operation wrapper: */
struct __ns3__getProductList
{
public:
	_ns1__getProductList *ns1__getProductList;	/* optional element of type ns1:getProductList */
};
#endif

#ifndef SOAP_TYPE___ns3__getBusinessDetails
#define SOAP_TYPE___ns3__getBusinessDetails (72)
/* Operation wrapper: */
struct __ns3__getBusinessDetails
{
public:
	_ns1__getBusinessDetails *ns1__getBusinessDetails;	/* optional element of type ns1:getBusinessDetails */
};
#endif

#ifndef SOAP_TYPE___ns4__getProductDetails
#define SOAP_TYPE___ns4__getProductDetails (74)
/* Operation wrapper: */
struct __ns4__getProductDetails
{
public:
	_ns1__getProductDetails *ns1__getProductDetails;	/* optional element of type ns1:getProductDetails */
};
#endif

#ifndef SOAP_TYPE___ns4__hello
#define SOAP_TYPE___ns4__hello (76)
/* Operation wrapper: */
struct __ns4__hello
{
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE___ns4__getCategoryList
#define SOAP_TYPE___ns4__getCategoryList (78)
/* Operation wrapper: */
struct __ns4__getCategoryList
{
public:
	_ns1__getCategoryList *ns1__getCategoryList;	/* optional element of type ns1:getCategoryList */
};
#endif

#ifndef SOAP_TYPE___ns4__getBusinessList
#define SOAP_TYPE___ns4__getBusinessList (80)
/* Operation wrapper: */
struct __ns4__getBusinessList
{
public:
	_ns1__getBusinessList *ns1__getBusinessList;	/* optional element of type ns1:getBusinessList */
};
#endif

#ifndef SOAP_TYPE___ns4__getProductList
#define SOAP_TYPE___ns4__getProductList (82)
/* Operation wrapper: */
struct __ns4__getProductList
{
public:
	_ns1__getProductList *ns1__getProductList;	/* optional element of type ns1:getProductList */
};
#endif

#ifndef SOAP_TYPE___ns4__getBusinessDetails
#define SOAP_TYPE___ns4__getBusinessDetails (84)
/* Operation wrapper: */
struct __ns4__getBusinessDetails
{
public:
	_ns1__getBusinessDetails *ns1__getBusinessDetails;	/* optional element of type ns1:getBusinessDetails */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (85)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (86)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (88)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (91)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (92)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Typedef Synonyms                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__getProductDetails(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getProductDetails *ns1__getProductDetails, _ns1__getProductDetailsResponse *ns1__getProductDetailsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__hello(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__helloResponse *ns1__helloResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__getCategoryList(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getCategoryList *ns1__getCategoryList, _ns1__getCategoryListResponse *ns1__getCategoryListResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__getBusinessList(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getBusinessList *ns1__getBusinessList, _ns1__getBusinessListResponse *ns1__getBusinessListResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__getProductList(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getProductList *ns1__getProductList, _ns1__getProductListResponse *ns1__getProductListResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__getBusinessDetails(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getBusinessDetails *ns1__getBusinessDetails, _ns1__getBusinessDetailsResponse *ns1__getBusinessDetailsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns4__getProductDetails(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getProductDetails *ns1__getProductDetails, _ns1__getProductDetailsResponse *ns1__getProductDetailsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns4__hello(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__helloResponse *ns1__helloResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns4__getCategoryList(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getCategoryList *ns1__getCategoryList, _ns1__getCategoryListResponse *ns1__getCategoryListResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns4__getBusinessList(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getBusinessList *ns1__getBusinessList, _ns1__getBusinessListResponse *ns1__getBusinessListResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns4__getProductList(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getProductList *ns1__getProductList, _ns1__getProductListResponse *ns1__getProductListResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns4__getBusinessDetails(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getBusinessDetails *ns1__getBusinessDetails, _ns1__getBusinessDetailsResponse *ns1__getBusinessDetailsResponse);

#endif

/* End of soapStub.h */
