/* soapH.h
   Generated by gSOAP 2.7.11 from ../../IMobile.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_float
#define SOAP_TYPE_float (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_float(struct soap*, float *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_float(struct soap*, const float *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_get_float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_float(struct soap*, const char*, float *, const char*);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_std__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__string(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getProductListResponse
#define SOAP_TYPE__ns1__getProductListResponse (26)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getProductListResponse(struct soap*, const char*, int, const _ns1__getProductListResponse *, const char*);
SOAP_FMAC3 _ns1__getProductListResponse * SOAP_FMAC4 soap_get__ns1__getProductListResponse(struct soap*, _ns1__getProductListResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__getProductListResponse * SOAP_FMAC4 soap_in__ns1__getProductListResponse(struct soap*, const char*, _ns1__getProductListResponse *, const char*);
SOAP_FMAC5 _ns1__getProductListResponse * SOAP_FMAC6 soap_new__ns1__getProductListResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getProductListResponse(struct soap*, _ns1__getProductListResponse*);
SOAP_FMAC3 _ns1__getProductListResponse * SOAP_FMAC4 soap_instantiate__ns1__getProductListResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getProductListResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getProductList
#define SOAP_TYPE__ns1__getProductList (25)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getProductList(struct soap*, const char*, int, const _ns1__getProductList *, const char*);
SOAP_FMAC3 _ns1__getProductList * SOAP_FMAC4 soap_get__ns1__getProductList(struct soap*, _ns1__getProductList *, const char*, const char*);
SOAP_FMAC3 _ns1__getProductList * SOAP_FMAC4 soap_in__ns1__getProductList(struct soap*, const char*, _ns1__getProductList *, const char*);
SOAP_FMAC5 _ns1__getProductList * SOAP_FMAC6 soap_new__ns1__getProductList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getProductList(struct soap*, _ns1__getProductList*);
SOAP_FMAC3 _ns1__getProductList * SOAP_FMAC4 soap_instantiate__ns1__getProductList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getProductList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getProductDetailsResponse
#define SOAP_TYPE__ns1__getProductDetailsResponse (24)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getProductDetailsResponse(struct soap*, const char*, int, const _ns1__getProductDetailsResponse *, const char*);
SOAP_FMAC3 _ns1__getProductDetailsResponse * SOAP_FMAC4 soap_get__ns1__getProductDetailsResponse(struct soap*, _ns1__getProductDetailsResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__getProductDetailsResponse * SOAP_FMAC4 soap_in__ns1__getProductDetailsResponse(struct soap*, const char*, _ns1__getProductDetailsResponse *, const char*);
SOAP_FMAC5 _ns1__getProductDetailsResponse * SOAP_FMAC6 soap_new__ns1__getProductDetailsResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getProductDetailsResponse(struct soap*, _ns1__getProductDetailsResponse*);
SOAP_FMAC3 _ns1__getProductDetailsResponse * SOAP_FMAC4 soap_instantiate__ns1__getProductDetailsResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getProductDetailsResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getProductDetails
#define SOAP_TYPE__ns1__getProductDetails (23)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getProductDetails(struct soap*, const char*, int, const _ns1__getProductDetails *, const char*);
SOAP_FMAC3 _ns1__getProductDetails * SOAP_FMAC4 soap_get__ns1__getProductDetails(struct soap*, _ns1__getProductDetails *, const char*, const char*);
SOAP_FMAC3 _ns1__getProductDetails * SOAP_FMAC4 soap_in__ns1__getProductDetails(struct soap*, const char*, _ns1__getProductDetails *, const char*);
SOAP_FMAC5 _ns1__getProductDetails * SOAP_FMAC6 soap_new__ns1__getProductDetails(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getProductDetails(struct soap*, _ns1__getProductDetails*);
SOAP_FMAC3 _ns1__getProductDetails * SOAP_FMAC4 soap_instantiate__ns1__getProductDetails(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getProductDetails(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getBusinessDetailsResponse
#define SOAP_TYPE__ns1__getBusinessDetailsResponse (22)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getBusinessDetailsResponse(struct soap*, const char*, int, const _ns1__getBusinessDetailsResponse *, const char*);
SOAP_FMAC3 _ns1__getBusinessDetailsResponse * SOAP_FMAC4 soap_get__ns1__getBusinessDetailsResponse(struct soap*, _ns1__getBusinessDetailsResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__getBusinessDetailsResponse * SOAP_FMAC4 soap_in__ns1__getBusinessDetailsResponse(struct soap*, const char*, _ns1__getBusinessDetailsResponse *, const char*);
SOAP_FMAC5 _ns1__getBusinessDetailsResponse * SOAP_FMAC6 soap_new__ns1__getBusinessDetailsResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getBusinessDetailsResponse(struct soap*, _ns1__getBusinessDetailsResponse*);
SOAP_FMAC3 _ns1__getBusinessDetailsResponse * SOAP_FMAC4 soap_instantiate__ns1__getBusinessDetailsResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getBusinessDetailsResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getBusinessDetails
#define SOAP_TYPE__ns1__getBusinessDetails (21)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getBusinessDetails(struct soap*, const char*, int, const _ns1__getBusinessDetails *, const char*);
SOAP_FMAC3 _ns1__getBusinessDetails * SOAP_FMAC4 soap_get__ns1__getBusinessDetails(struct soap*, _ns1__getBusinessDetails *, const char*, const char*);
SOAP_FMAC3 _ns1__getBusinessDetails * SOAP_FMAC4 soap_in__ns1__getBusinessDetails(struct soap*, const char*, _ns1__getBusinessDetails *, const char*);
SOAP_FMAC5 _ns1__getBusinessDetails * SOAP_FMAC6 soap_new__ns1__getBusinessDetails(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getBusinessDetails(struct soap*, _ns1__getBusinessDetails*);
SOAP_FMAC3 _ns1__getBusinessDetails * SOAP_FMAC4 soap_instantiate__ns1__getBusinessDetails(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getBusinessDetails(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getCategoryListResponse
#define SOAP_TYPE__ns1__getCategoryListResponse (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getCategoryListResponse(struct soap*, const char*, int, const _ns1__getCategoryListResponse *, const char*);
SOAP_FMAC3 _ns1__getCategoryListResponse * SOAP_FMAC4 soap_get__ns1__getCategoryListResponse(struct soap*, _ns1__getCategoryListResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__getCategoryListResponse * SOAP_FMAC4 soap_in__ns1__getCategoryListResponse(struct soap*, const char*, _ns1__getCategoryListResponse *, const char*);
SOAP_FMAC5 _ns1__getCategoryListResponse * SOAP_FMAC6 soap_new__ns1__getCategoryListResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getCategoryListResponse(struct soap*, _ns1__getCategoryListResponse*);
SOAP_FMAC3 _ns1__getCategoryListResponse * SOAP_FMAC4 soap_instantiate__ns1__getCategoryListResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getCategoryListResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getCategoryList
#define SOAP_TYPE__ns1__getCategoryList (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getCategoryList(struct soap*, const char*, int, const _ns1__getCategoryList *, const char*);
SOAP_FMAC3 _ns1__getCategoryList * SOAP_FMAC4 soap_get__ns1__getCategoryList(struct soap*, _ns1__getCategoryList *, const char*, const char*);
SOAP_FMAC3 _ns1__getCategoryList * SOAP_FMAC4 soap_in__ns1__getCategoryList(struct soap*, const char*, _ns1__getCategoryList *, const char*);
SOAP_FMAC5 _ns1__getCategoryList * SOAP_FMAC6 soap_new__ns1__getCategoryList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getCategoryList(struct soap*, _ns1__getCategoryList*);
SOAP_FMAC3 _ns1__getCategoryList * SOAP_FMAC4 soap_instantiate__ns1__getCategoryList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getCategoryList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getBusinessListResponse
#define SOAP_TYPE__ns1__getBusinessListResponse (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getBusinessListResponse(struct soap*, const char*, int, const _ns1__getBusinessListResponse *, const char*);
SOAP_FMAC3 _ns1__getBusinessListResponse * SOAP_FMAC4 soap_get__ns1__getBusinessListResponse(struct soap*, _ns1__getBusinessListResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__getBusinessListResponse * SOAP_FMAC4 soap_in__ns1__getBusinessListResponse(struct soap*, const char*, _ns1__getBusinessListResponse *, const char*);
SOAP_FMAC5 _ns1__getBusinessListResponse * SOAP_FMAC6 soap_new__ns1__getBusinessListResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getBusinessListResponse(struct soap*, _ns1__getBusinessListResponse*);
SOAP_FMAC3 _ns1__getBusinessListResponse * SOAP_FMAC4 soap_instantiate__ns1__getBusinessListResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getBusinessListResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__getBusinessList
#define SOAP_TYPE__ns1__getBusinessList (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getBusinessList(struct soap*, const char*, int, const _ns1__getBusinessList *, const char*);
SOAP_FMAC3 _ns1__getBusinessList * SOAP_FMAC4 soap_get__ns1__getBusinessList(struct soap*, _ns1__getBusinessList *, const char*, const char*);
SOAP_FMAC3 _ns1__getBusinessList * SOAP_FMAC4 soap_in__ns1__getBusinessList(struct soap*, const char*, _ns1__getBusinessList *, const char*);
SOAP_FMAC5 _ns1__getBusinessList * SOAP_FMAC6 soap_new__ns1__getBusinessList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getBusinessList(struct soap*, _ns1__getBusinessList*);
SOAP_FMAC3 _ns1__getBusinessList * SOAP_FMAC4 soap_instantiate__ns1__getBusinessList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getBusinessList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__MProductOffer
#define SOAP_TYPE_ns2__MProductOffer (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__MProductOffer(struct soap*, const char*, int, const ns2__MProductOffer *, const char*);
SOAP_FMAC3 ns2__MProductOffer * SOAP_FMAC4 soap_get_ns2__MProductOffer(struct soap*, ns2__MProductOffer *, const char*, const char*);
SOAP_FMAC3 ns2__MProductOffer * SOAP_FMAC4 soap_in_ns2__MProductOffer(struct soap*, const char*, ns2__MProductOffer *, const char*);
SOAP_FMAC5 ns2__MProductOffer * SOAP_FMAC6 soap_new_ns2__MProductOffer(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__MProductOffer(struct soap*, ns2__MProductOffer*);
SOAP_FMAC3 ns2__MProductOffer * SOAP_FMAC4 soap_instantiate_ns2__MProductOffer(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__MProductOffer(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__MDetailedProduct
#define SOAP_TYPE_ns2__MDetailedProduct (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__MDetailedProduct(struct soap*, const char*, int, const ns2__MDetailedProduct *, const char*);
SOAP_FMAC3 ns2__MDetailedProduct * SOAP_FMAC4 soap_get_ns2__MDetailedProduct(struct soap*, ns2__MDetailedProduct *, const char*, const char*);
SOAP_FMAC3 ns2__MDetailedProduct * SOAP_FMAC4 soap_in_ns2__MDetailedProduct(struct soap*, const char*, ns2__MDetailedProduct *, const char*);
SOAP_FMAC5 ns2__MDetailedProduct * SOAP_FMAC6 soap_new_ns2__MDetailedProduct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__MDetailedProduct(struct soap*, ns2__MDetailedProduct*);
SOAP_FMAC3 ns2__MDetailedProduct * SOAP_FMAC4 soap_instantiate_ns2__MDetailedProduct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__MDetailedProduct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__MProduct
#define SOAP_TYPE_ns2__MProduct (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__MProduct(struct soap*, const char*, int, const ns2__MProduct *, const char*);
SOAP_FMAC3 ns2__MProduct * SOAP_FMAC4 soap_get_ns2__MProduct(struct soap*, ns2__MProduct *, const char*, const char*);
SOAP_FMAC3 ns2__MProduct * SOAP_FMAC4 soap_in_ns2__MProduct(struct soap*, const char*, ns2__MProduct *, const char*);
SOAP_FMAC5 ns2__MProduct * SOAP_FMAC6 soap_new_ns2__MProduct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__MProduct(struct soap*, ns2__MProduct*);
SOAP_FMAC3 ns2__MProduct * SOAP_FMAC4 soap_instantiate_ns2__MProduct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__MProduct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__MContactInfo
#define SOAP_TYPE_ns2__MContactInfo (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__MContactInfo(struct soap*, const char*, int, const ns2__MContactInfo *, const char*);
SOAP_FMAC3 ns2__MContactInfo * SOAP_FMAC4 soap_get_ns2__MContactInfo(struct soap*, ns2__MContactInfo *, const char*, const char*);
SOAP_FMAC3 ns2__MContactInfo * SOAP_FMAC4 soap_in_ns2__MContactInfo(struct soap*, const char*, ns2__MContactInfo *, const char*);
SOAP_FMAC5 ns2__MContactInfo * SOAP_FMAC6 soap_new_ns2__MContactInfo(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__MContactInfo(struct soap*, ns2__MContactInfo*);
SOAP_FMAC3 ns2__MContactInfo * SOAP_FMAC4 soap_instantiate_ns2__MContactInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__MContactInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__MAddress
#define SOAP_TYPE_ns2__MAddress (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__MAddress(struct soap*, const char*, int, const ns2__MAddress *, const char*);
SOAP_FMAC3 ns2__MAddress * SOAP_FMAC4 soap_get_ns2__MAddress(struct soap*, ns2__MAddress *, const char*, const char*);
SOAP_FMAC3 ns2__MAddress * SOAP_FMAC4 soap_in_ns2__MAddress(struct soap*, const char*, ns2__MAddress *, const char*);
SOAP_FMAC5 ns2__MAddress * SOAP_FMAC6 soap_new_ns2__MAddress(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__MAddress(struct soap*, ns2__MAddress*);
SOAP_FMAC3 ns2__MAddress * SOAP_FMAC4 soap_instantiate_ns2__MAddress(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__MAddress(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__MDetailedBusinessCard
#define SOAP_TYPE_ns2__MDetailedBusinessCard (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__MDetailedBusinessCard(struct soap*, const char*, int, const ns2__MDetailedBusinessCard *, const char*);
SOAP_FMAC3 ns2__MDetailedBusinessCard * SOAP_FMAC4 soap_get_ns2__MDetailedBusinessCard(struct soap*, ns2__MDetailedBusinessCard *, const char*, const char*);
SOAP_FMAC3 ns2__MDetailedBusinessCard * SOAP_FMAC4 soap_in_ns2__MDetailedBusinessCard(struct soap*, const char*, ns2__MDetailedBusinessCard *, const char*);
SOAP_FMAC5 ns2__MDetailedBusinessCard * SOAP_FMAC6 soap_new_ns2__MDetailedBusinessCard(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__MDetailedBusinessCard(struct soap*, ns2__MDetailedBusinessCard*);
SOAP_FMAC3 ns2__MDetailedBusinessCard * SOAP_FMAC4 soap_instantiate_ns2__MDetailedBusinessCard(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__MDetailedBusinessCard(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__MCategory
#define SOAP_TYPE_ns2__MCategory (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__MCategory(struct soap*, const char*, int, const ns2__MCategory *, const char*);
SOAP_FMAC3 ns2__MCategory * SOAP_FMAC4 soap_get_ns2__MCategory(struct soap*, ns2__MCategory *, const char*, const char*);
SOAP_FMAC3 ns2__MCategory * SOAP_FMAC4 soap_in_ns2__MCategory(struct soap*, const char*, ns2__MCategory *, const char*);
SOAP_FMAC5 ns2__MCategory * SOAP_FMAC6 soap_new_ns2__MCategory(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__MCategory(struct soap*, ns2__MCategory*);
SOAP_FMAC3 ns2__MCategory * SOAP_FMAC4 soap_instantiate_ns2__MCategory(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__MCategory(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__MBusinessCard
#define SOAP_TYPE_ns2__MBusinessCard (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__MBusinessCard(struct soap*, const char*, int, const ns2__MBusinessCard *, const char*);
SOAP_FMAC3 ns2__MBusinessCard * SOAP_FMAC4 soap_get_ns2__MBusinessCard(struct soap*, ns2__MBusinessCard *, const char*, const char*);
SOAP_FMAC3 ns2__MBusinessCard * SOAP_FMAC4 soap_in_ns2__MBusinessCard(struct soap*, const char*, ns2__MBusinessCard *, const char*);
SOAP_FMAC5 ns2__MBusinessCard * SOAP_FMAC6 soap_new_ns2__MBusinessCard(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__MBusinessCard(struct soap*, ns2__MBusinessCard*);
SOAP_FMAC3 ns2__MBusinessCard * SOAP_FMAC4 soap_instantiate_ns2__MBusinessCard(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__MBusinessCard(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__MItem
#define SOAP_TYPE_ns2__MItem (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__MItem(struct soap*, const char*, int, const ns2__MItem *, const char*);
SOAP_FMAC3 ns2__MItem * SOAP_FMAC4 soap_get_ns2__MItem(struct soap*, ns2__MItem *, const char*, const char*);
SOAP_FMAC3 ns2__MItem * SOAP_FMAC4 soap_in_ns2__MItem(struct soap*, const char*, ns2__MItem *, const char*);
SOAP_FMAC5 ns2__MItem * SOAP_FMAC6 soap_new_ns2__MItem(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__MItem(struct soap*, ns2__MItem*);
SOAP_FMAC3 ns2__MItem * SOAP_FMAC4 soap_instantiate_ns2__MItem(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__MItem(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (82)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (81)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns4__getBusinessDetails
#define SOAP_TYPE___ns4__getBusinessDetails (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns4__getBusinessDetails(struct soap*, struct __ns4__getBusinessDetails *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns4__getBusinessDetails(struct soap*, const struct __ns4__getBusinessDetails *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns4__getBusinessDetails(struct soap*, const struct __ns4__getBusinessDetails *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns4__getBusinessDetails(struct soap*, const char*, int, const struct __ns4__getBusinessDetails *, const char*);
SOAP_FMAC3 struct __ns4__getBusinessDetails * SOAP_FMAC4 soap_get___ns4__getBusinessDetails(struct soap*, struct __ns4__getBusinessDetails *, const char*, const char*);
SOAP_FMAC3 struct __ns4__getBusinessDetails * SOAP_FMAC4 soap_in___ns4__getBusinessDetails(struct soap*, const char*, struct __ns4__getBusinessDetails *, const char*);
SOAP_FMAC5 struct __ns4__getBusinessDetails * SOAP_FMAC6 soap_new___ns4__getBusinessDetails(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns4__getBusinessDetails(struct soap*, struct __ns4__getBusinessDetails*);
SOAP_FMAC3 struct __ns4__getBusinessDetails * SOAP_FMAC4 soap_instantiate___ns4__getBusinessDetails(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns4__getBusinessDetails(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns4__getProductList
#define SOAP_TYPE___ns4__getProductList (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns4__getProductList(struct soap*, struct __ns4__getProductList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns4__getProductList(struct soap*, const struct __ns4__getProductList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns4__getProductList(struct soap*, const struct __ns4__getProductList *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns4__getProductList(struct soap*, const char*, int, const struct __ns4__getProductList *, const char*);
SOAP_FMAC3 struct __ns4__getProductList * SOAP_FMAC4 soap_get___ns4__getProductList(struct soap*, struct __ns4__getProductList *, const char*, const char*);
SOAP_FMAC3 struct __ns4__getProductList * SOAP_FMAC4 soap_in___ns4__getProductList(struct soap*, const char*, struct __ns4__getProductList *, const char*);
SOAP_FMAC5 struct __ns4__getProductList * SOAP_FMAC6 soap_new___ns4__getProductList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns4__getProductList(struct soap*, struct __ns4__getProductList*);
SOAP_FMAC3 struct __ns4__getProductList * SOAP_FMAC4 soap_instantiate___ns4__getProductList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns4__getProductList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns4__getBusinessList
#define SOAP_TYPE___ns4__getBusinessList (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns4__getBusinessList(struct soap*, struct __ns4__getBusinessList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns4__getBusinessList(struct soap*, const struct __ns4__getBusinessList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns4__getBusinessList(struct soap*, const struct __ns4__getBusinessList *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns4__getBusinessList(struct soap*, const char*, int, const struct __ns4__getBusinessList *, const char*);
SOAP_FMAC3 struct __ns4__getBusinessList * SOAP_FMAC4 soap_get___ns4__getBusinessList(struct soap*, struct __ns4__getBusinessList *, const char*, const char*);
SOAP_FMAC3 struct __ns4__getBusinessList * SOAP_FMAC4 soap_in___ns4__getBusinessList(struct soap*, const char*, struct __ns4__getBusinessList *, const char*);
SOAP_FMAC5 struct __ns4__getBusinessList * SOAP_FMAC6 soap_new___ns4__getBusinessList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns4__getBusinessList(struct soap*, struct __ns4__getBusinessList*);
SOAP_FMAC3 struct __ns4__getBusinessList * SOAP_FMAC4 soap_instantiate___ns4__getBusinessList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns4__getBusinessList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns4__getCategoryList
#define SOAP_TYPE___ns4__getCategoryList (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns4__getCategoryList(struct soap*, struct __ns4__getCategoryList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns4__getCategoryList(struct soap*, const struct __ns4__getCategoryList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns4__getCategoryList(struct soap*, const struct __ns4__getCategoryList *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns4__getCategoryList(struct soap*, const char*, int, const struct __ns4__getCategoryList *, const char*);
SOAP_FMAC3 struct __ns4__getCategoryList * SOAP_FMAC4 soap_get___ns4__getCategoryList(struct soap*, struct __ns4__getCategoryList *, const char*, const char*);
SOAP_FMAC3 struct __ns4__getCategoryList * SOAP_FMAC4 soap_in___ns4__getCategoryList(struct soap*, const char*, struct __ns4__getCategoryList *, const char*);
SOAP_FMAC5 struct __ns4__getCategoryList * SOAP_FMAC6 soap_new___ns4__getCategoryList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns4__getCategoryList(struct soap*, struct __ns4__getCategoryList*);
SOAP_FMAC3 struct __ns4__getCategoryList * SOAP_FMAC4 soap_instantiate___ns4__getCategoryList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns4__getCategoryList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns4__getProductDetails
#define SOAP_TYPE___ns4__getProductDetails (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns4__getProductDetails(struct soap*, struct __ns4__getProductDetails *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns4__getProductDetails(struct soap*, const struct __ns4__getProductDetails *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns4__getProductDetails(struct soap*, const struct __ns4__getProductDetails *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns4__getProductDetails(struct soap*, const char*, int, const struct __ns4__getProductDetails *, const char*);
SOAP_FMAC3 struct __ns4__getProductDetails * SOAP_FMAC4 soap_get___ns4__getProductDetails(struct soap*, struct __ns4__getProductDetails *, const char*, const char*);
SOAP_FMAC3 struct __ns4__getProductDetails * SOAP_FMAC4 soap_in___ns4__getProductDetails(struct soap*, const char*, struct __ns4__getProductDetails *, const char*);
SOAP_FMAC5 struct __ns4__getProductDetails * SOAP_FMAC6 soap_new___ns4__getProductDetails(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns4__getProductDetails(struct soap*, struct __ns4__getProductDetails*);
SOAP_FMAC3 struct __ns4__getProductDetails * SOAP_FMAC4 soap_instantiate___ns4__getProductDetails(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns4__getProductDetails(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__getBusinessDetails
#define SOAP_TYPE___ns3__getBusinessDetails (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__getBusinessDetails(struct soap*, struct __ns3__getBusinessDetails *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__getBusinessDetails(struct soap*, const struct __ns3__getBusinessDetails *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__getBusinessDetails(struct soap*, const struct __ns3__getBusinessDetails *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__getBusinessDetails(struct soap*, const char*, int, const struct __ns3__getBusinessDetails *, const char*);
SOAP_FMAC3 struct __ns3__getBusinessDetails * SOAP_FMAC4 soap_get___ns3__getBusinessDetails(struct soap*, struct __ns3__getBusinessDetails *, const char*, const char*);
SOAP_FMAC3 struct __ns3__getBusinessDetails * SOAP_FMAC4 soap_in___ns3__getBusinessDetails(struct soap*, const char*, struct __ns3__getBusinessDetails *, const char*);
SOAP_FMAC5 struct __ns3__getBusinessDetails * SOAP_FMAC6 soap_new___ns3__getBusinessDetails(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns3__getBusinessDetails(struct soap*, struct __ns3__getBusinessDetails*);
SOAP_FMAC3 struct __ns3__getBusinessDetails * SOAP_FMAC4 soap_instantiate___ns3__getBusinessDetails(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__getBusinessDetails(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__getProductList
#define SOAP_TYPE___ns3__getProductList (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__getProductList(struct soap*, struct __ns3__getProductList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__getProductList(struct soap*, const struct __ns3__getProductList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__getProductList(struct soap*, const struct __ns3__getProductList *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__getProductList(struct soap*, const char*, int, const struct __ns3__getProductList *, const char*);
SOAP_FMAC3 struct __ns3__getProductList * SOAP_FMAC4 soap_get___ns3__getProductList(struct soap*, struct __ns3__getProductList *, const char*, const char*);
SOAP_FMAC3 struct __ns3__getProductList * SOAP_FMAC4 soap_in___ns3__getProductList(struct soap*, const char*, struct __ns3__getProductList *, const char*);
SOAP_FMAC5 struct __ns3__getProductList * SOAP_FMAC6 soap_new___ns3__getProductList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns3__getProductList(struct soap*, struct __ns3__getProductList*);
SOAP_FMAC3 struct __ns3__getProductList * SOAP_FMAC4 soap_instantiate___ns3__getProductList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__getProductList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__getBusinessList
#define SOAP_TYPE___ns3__getBusinessList (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__getBusinessList(struct soap*, struct __ns3__getBusinessList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__getBusinessList(struct soap*, const struct __ns3__getBusinessList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__getBusinessList(struct soap*, const struct __ns3__getBusinessList *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__getBusinessList(struct soap*, const char*, int, const struct __ns3__getBusinessList *, const char*);
SOAP_FMAC3 struct __ns3__getBusinessList * SOAP_FMAC4 soap_get___ns3__getBusinessList(struct soap*, struct __ns3__getBusinessList *, const char*, const char*);
SOAP_FMAC3 struct __ns3__getBusinessList * SOAP_FMAC4 soap_in___ns3__getBusinessList(struct soap*, const char*, struct __ns3__getBusinessList *, const char*);
SOAP_FMAC5 struct __ns3__getBusinessList * SOAP_FMAC6 soap_new___ns3__getBusinessList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns3__getBusinessList(struct soap*, struct __ns3__getBusinessList*);
SOAP_FMAC3 struct __ns3__getBusinessList * SOAP_FMAC4 soap_instantiate___ns3__getBusinessList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__getBusinessList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__getCategoryList
#define SOAP_TYPE___ns3__getCategoryList (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__getCategoryList(struct soap*, struct __ns3__getCategoryList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__getCategoryList(struct soap*, const struct __ns3__getCategoryList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__getCategoryList(struct soap*, const struct __ns3__getCategoryList *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__getCategoryList(struct soap*, const char*, int, const struct __ns3__getCategoryList *, const char*);
SOAP_FMAC3 struct __ns3__getCategoryList * SOAP_FMAC4 soap_get___ns3__getCategoryList(struct soap*, struct __ns3__getCategoryList *, const char*, const char*);
SOAP_FMAC3 struct __ns3__getCategoryList * SOAP_FMAC4 soap_in___ns3__getCategoryList(struct soap*, const char*, struct __ns3__getCategoryList *, const char*);
SOAP_FMAC5 struct __ns3__getCategoryList * SOAP_FMAC6 soap_new___ns3__getCategoryList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns3__getCategoryList(struct soap*, struct __ns3__getCategoryList*);
SOAP_FMAC3 struct __ns3__getCategoryList * SOAP_FMAC4 soap_instantiate___ns3__getCategoryList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__getCategoryList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__getProductDetails
#define SOAP_TYPE___ns3__getProductDetails (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__getProductDetails(struct soap*, struct __ns3__getProductDetails *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__getProductDetails(struct soap*, const struct __ns3__getProductDetails *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__getProductDetails(struct soap*, const struct __ns3__getProductDetails *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__getProductDetails(struct soap*, const char*, int, const struct __ns3__getProductDetails *, const char*);
SOAP_FMAC3 struct __ns3__getProductDetails * SOAP_FMAC4 soap_get___ns3__getProductDetails(struct soap*, struct __ns3__getProductDetails *, const char*, const char*);
SOAP_FMAC3 struct __ns3__getProductDetails * SOAP_FMAC4 soap_in___ns3__getProductDetails(struct soap*, const char*, struct __ns3__getProductDetails *, const char*);
SOAP_FMAC5 struct __ns3__getProductDetails * SOAP_FMAC6 soap_new___ns3__getProductDetails(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns3__getProductDetails(struct soap*, struct __ns3__getProductDetails*);
SOAP_FMAC3 struct __ns3__getProductDetails * SOAP_FMAC4 soap_instantiate___ns3__getProductDetails(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__getProductDetails(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (84)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (83)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns1__getBusinessDetailsResponse
#define SOAP_TYPE_PointerTo_ns1__getBusinessDetailsResponse (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getBusinessDetailsResponse(struct soap*, _ns1__getBusinessDetailsResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getBusinessDetailsResponse(struct soap*, _ns1__getBusinessDetailsResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getBusinessDetailsResponse(struct soap*, const char *, int, _ns1__getBusinessDetailsResponse *const*, const char *);
SOAP_FMAC3 _ns1__getBusinessDetailsResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__getBusinessDetailsResponse(struct soap*, _ns1__getBusinessDetailsResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__getBusinessDetailsResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__getBusinessDetailsResponse(struct soap*, const char*, _ns1__getBusinessDetailsResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getBusinessDetails
#define SOAP_TYPE_PointerTo_ns1__getBusinessDetails (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getBusinessDetails(struct soap*, _ns1__getBusinessDetails *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getBusinessDetails(struct soap*, _ns1__getBusinessDetails *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getBusinessDetails(struct soap*, const char *, int, _ns1__getBusinessDetails *const*, const char *);
SOAP_FMAC3 _ns1__getBusinessDetails ** SOAP_FMAC4 soap_get_PointerTo_ns1__getBusinessDetails(struct soap*, _ns1__getBusinessDetails **, const char*, const char*);
SOAP_FMAC3 _ns1__getBusinessDetails ** SOAP_FMAC4 soap_in_PointerTo_ns1__getBusinessDetails(struct soap*, const char*, _ns1__getBusinessDetails **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getProductListResponse
#define SOAP_TYPE_PointerTo_ns1__getProductListResponse (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getProductListResponse(struct soap*, _ns1__getProductListResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getProductListResponse(struct soap*, _ns1__getProductListResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getProductListResponse(struct soap*, const char *, int, _ns1__getProductListResponse *const*, const char *);
SOAP_FMAC3 _ns1__getProductListResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__getProductListResponse(struct soap*, _ns1__getProductListResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__getProductListResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__getProductListResponse(struct soap*, const char*, _ns1__getProductListResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getProductList
#define SOAP_TYPE_PointerTo_ns1__getProductList (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getProductList(struct soap*, _ns1__getProductList *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getProductList(struct soap*, _ns1__getProductList *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getProductList(struct soap*, const char *, int, _ns1__getProductList *const*, const char *);
SOAP_FMAC3 _ns1__getProductList ** SOAP_FMAC4 soap_get_PointerTo_ns1__getProductList(struct soap*, _ns1__getProductList **, const char*, const char*);
SOAP_FMAC3 _ns1__getProductList ** SOAP_FMAC4 soap_in_PointerTo_ns1__getProductList(struct soap*, const char*, _ns1__getProductList **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getBusinessListResponse
#define SOAP_TYPE_PointerTo_ns1__getBusinessListResponse (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getBusinessListResponse(struct soap*, _ns1__getBusinessListResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getBusinessListResponse(struct soap*, _ns1__getBusinessListResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getBusinessListResponse(struct soap*, const char *, int, _ns1__getBusinessListResponse *const*, const char *);
SOAP_FMAC3 _ns1__getBusinessListResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__getBusinessListResponse(struct soap*, _ns1__getBusinessListResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__getBusinessListResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__getBusinessListResponse(struct soap*, const char*, _ns1__getBusinessListResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getBusinessList
#define SOAP_TYPE_PointerTo_ns1__getBusinessList (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getBusinessList(struct soap*, _ns1__getBusinessList *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getBusinessList(struct soap*, _ns1__getBusinessList *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getBusinessList(struct soap*, const char *, int, _ns1__getBusinessList *const*, const char *);
SOAP_FMAC3 _ns1__getBusinessList ** SOAP_FMAC4 soap_get_PointerTo_ns1__getBusinessList(struct soap*, _ns1__getBusinessList **, const char*, const char*);
SOAP_FMAC3 _ns1__getBusinessList ** SOAP_FMAC4 soap_in_PointerTo_ns1__getBusinessList(struct soap*, const char*, _ns1__getBusinessList **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getCategoryListResponse
#define SOAP_TYPE_PointerTo_ns1__getCategoryListResponse (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getCategoryListResponse(struct soap*, _ns1__getCategoryListResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getCategoryListResponse(struct soap*, _ns1__getCategoryListResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getCategoryListResponse(struct soap*, const char *, int, _ns1__getCategoryListResponse *const*, const char *);
SOAP_FMAC3 _ns1__getCategoryListResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__getCategoryListResponse(struct soap*, _ns1__getCategoryListResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__getCategoryListResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__getCategoryListResponse(struct soap*, const char*, _ns1__getCategoryListResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getCategoryList
#define SOAP_TYPE_PointerTo_ns1__getCategoryList (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getCategoryList(struct soap*, _ns1__getCategoryList *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getCategoryList(struct soap*, _ns1__getCategoryList *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getCategoryList(struct soap*, const char *, int, _ns1__getCategoryList *const*, const char *);
SOAP_FMAC3 _ns1__getCategoryList ** SOAP_FMAC4 soap_get_PointerTo_ns1__getCategoryList(struct soap*, _ns1__getCategoryList **, const char*, const char*);
SOAP_FMAC3 _ns1__getCategoryList ** SOAP_FMAC4 soap_in_PointerTo_ns1__getCategoryList(struct soap*, const char*, _ns1__getCategoryList **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getProductDetailsResponse
#define SOAP_TYPE_PointerTo_ns1__getProductDetailsResponse (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getProductDetailsResponse(struct soap*, _ns1__getProductDetailsResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getProductDetailsResponse(struct soap*, _ns1__getProductDetailsResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getProductDetailsResponse(struct soap*, const char *, int, _ns1__getProductDetailsResponse *const*, const char *);
SOAP_FMAC3 _ns1__getProductDetailsResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__getProductDetailsResponse(struct soap*, _ns1__getProductDetailsResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__getProductDetailsResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__getProductDetailsResponse(struct soap*, const char*, _ns1__getProductDetailsResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getProductDetails
#define SOAP_TYPE_PointerTo_ns1__getProductDetails (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getProductDetails(struct soap*, _ns1__getProductDetails *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getProductDetails(struct soap*, _ns1__getProductDetails *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getProductDetails(struct soap*, const char *, int, _ns1__getProductDetails *const*, const char *);
SOAP_FMAC3 _ns1__getProductDetails ** SOAP_FMAC4 soap_get_PointerTo_ns1__getProductDetails(struct soap*, _ns1__getProductDetails **, const char*, const char*);
SOAP_FMAC3 _ns1__getProductDetails ** SOAP_FMAC4 soap_in_PointerTo_ns1__getProductDetails(struct soap*, const char*, _ns1__getProductDetails **, const char*);

#ifndef SOAP_TYPE_PointerTons2__MProductOffer
#define SOAP_TYPE_PointerTons2__MProductOffer (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__MProductOffer(struct soap*, ns2__MProductOffer *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__MProductOffer(struct soap*, ns2__MProductOffer *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__MProductOffer(struct soap*, const char *, int, ns2__MProductOffer *const*, const char *);
SOAP_FMAC3 ns2__MProductOffer ** SOAP_FMAC4 soap_get_PointerTons2__MProductOffer(struct soap*, ns2__MProductOffer **, const char*, const char*);
SOAP_FMAC3 ns2__MProductOffer ** SOAP_FMAC4 soap_in_PointerTons2__MProductOffer(struct soap*, const char*, ns2__MProductOffer **, const char*);

#ifndef SOAP_TYPE_PointerTons2__MContactInfo
#define SOAP_TYPE_PointerTons2__MContactInfo (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__MContactInfo(struct soap*, ns2__MContactInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__MContactInfo(struct soap*, ns2__MContactInfo *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__MContactInfo(struct soap*, const char *, int, ns2__MContactInfo *const*, const char *);
SOAP_FMAC3 ns2__MContactInfo ** SOAP_FMAC4 soap_get_PointerTons2__MContactInfo(struct soap*, ns2__MContactInfo **, const char*, const char*);
SOAP_FMAC3 ns2__MContactInfo ** SOAP_FMAC4 soap_in_PointerTons2__MContactInfo(struct soap*, const char*, ns2__MContactInfo **, const char*);

#ifndef SOAP_TYPE_PointerTons2__MAddress
#define SOAP_TYPE_PointerTons2__MAddress (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__MAddress(struct soap*, ns2__MAddress *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__MAddress(struct soap*, ns2__MAddress *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__MAddress(struct soap*, const char *, int, ns2__MAddress *const*, const char *);
SOAP_FMAC3 ns2__MAddress ** SOAP_FMAC4 soap_get_PointerTons2__MAddress(struct soap*, ns2__MAddress **, const char*, const char*);
SOAP_FMAC3 ns2__MAddress ** SOAP_FMAC4 soap_in_PointerTons2__MAddress(struct soap*, const char*, ns2__MAddress **, const char*);

#ifndef SOAP_TYPE_PointerTons2__MProduct
#define SOAP_TYPE_PointerTons2__MProduct (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__MProduct(struct soap*, ns2__MProduct *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__MProduct(struct soap*, ns2__MProduct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__MProduct(struct soap*, const char *, int, ns2__MProduct *const*, const char *);
SOAP_FMAC3 ns2__MProduct ** SOAP_FMAC4 soap_get_PointerTons2__MProduct(struct soap*, ns2__MProduct **, const char*, const char*);
SOAP_FMAC3 ns2__MProduct ** SOAP_FMAC4 soap_in_PointerTons2__MProduct(struct soap*, const char*, ns2__MProduct **, const char*);

#ifndef SOAP_TYPE_PointerTons2__MDetailedProduct
#define SOAP_TYPE_PointerTons2__MDetailedProduct (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__MDetailedProduct(struct soap*, ns2__MDetailedProduct *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__MDetailedProduct(struct soap*, ns2__MDetailedProduct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__MDetailedProduct(struct soap*, const char *, int, ns2__MDetailedProduct *const*, const char *);
SOAP_FMAC3 ns2__MDetailedProduct ** SOAP_FMAC4 soap_get_PointerTons2__MDetailedProduct(struct soap*, ns2__MDetailedProduct **, const char*, const char*);
SOAP_FMAC3 ns2__MDetailedProduct ** SOAP_FMAC4 soap_in_PointerTons2__MDetailedProduct(struct soap*, const char*, ns2__MDetailedProduct **, const char*);

#ifndef SOAP_TYPE_PointerTons2__MDetailedBusinessCard
#define SOAP_TYPE_PointerTons2__MDetailedBusinessCard (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__MDetailedBusinessCard(struct soap*, ns2__MDetailedBusinessCard *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__MDetailedBusinessCard(struct soap*, ns2__MDetailedBusinessCard *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__MDetailedBusinessCard(struct soap*, const char *, int, ns2__MDetailedBusinessCard *const*, const char *);
SOAP_FMAC3 ns2__MDetailedBusinessCard ** SOAP_FMAC4 soap_get_PointerTons2__MDetailedBusinessCard(struct soap*, ns2__MDetailedBusinessCard **, const char*, const char*);
SOAP_FMAC3 ns2__MDetailedBusinessCard ** SOAP_FMAC4 soap_in_PointerTons2__MDetailedBusinessCard(struct soap*, const char*, ns2__MDetailedBusinessCard **, const char*);

#ifndef SOAP_TYPE_PointerTons2__MBusinessCard
#define SOAP_TYPE_PointerTons2__MBusinessCard (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__MBusinessCard(struct soap*, ns2__MBusinessCard *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__MBusinessCard(struct soap*, ns2__MBusinessCard *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__MBusinessCard(struct soap*, const char *, int, ns2__MBusinessCard *const*, const char *);
SOAP_FMAC3 ns2__MBusinessCard ** SOAP_FMAC4 soap_get_PointerTons2__MBusinessCard(struct soap*, ns2__MBusinessCard **, const char*, const char*);
SOAP_FMAC3 ns2__MBusinessCard ** SOAP_FMAC4 soap_in_PointerTons2__MBusinessCard(struct soap*, const char*, ns2__MBusinessCard **, const char*);

#ifndef SOAP_TYPE_PointerTofloat
#define SOAP_TYPE_PointerTofloat (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTofloat(struct soap*, float *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTofloat(struct soap*, float *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTofloat(struct soap*, const char *, int, float *const*, const char *);
SOAP_FMAC3 float ** SOAP_FMAC4 soap_get_PointerTofloat(struct soap*, float **, const char*, const char*);
SOAP_FMAC3 float ** SOAP_FMAC4 soap_in_PointerTofloat(struct soap*, const char*, float **, const char*);

#ifndef SOAP_TYPE_PointerTons2__MCategory
#define SOAP_TYPE_PointerTons2__MCategory (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__MCategory(struct soap*, ns2__MCategory *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__MCategory(struct soap*, ns2__MCategory *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__MCategory(struct soap*, const char *, int, ns2__MCategory *const*, const char *);
SOAP_FMAC3 ns2__MCategory ** SOAP_FMAC4 soap_get_PointerTons2__MCategory(struct soap*, ns2__MCategory **, const char*, const char*);
SOAP_FMAC3 ns2__MCategory ** SOAP_FMAC4 soap_in_PointerTons2__MCategory(struct soap*, const char*, ns2__MCategory **, const char*);

#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons2__MProductOffer
#define SOAP_TYPE_std__vectorTemplateOfPointerTons2__MProductOffer (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons2__MProductOffer(struct soap*, std::vector<ns2__MProductOffer * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons2__MProductOffer(struct soap*, const std::vector<ns2__MProductOffer * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons2__MProductOffer(struct soap*, const char*, int, const std::vector<ns2__MProductOffer * >*, const char*);
SOAP_FMAC3 std::vector<ns2__MProductOffer * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons2__MProductOffer(struct soap*, const char*, std::vector<ns2__MProductOffer * >*, const char*);
SOAP_FMAC5 std::vector<ns2__MProductOffer * > * SOAP_FMAC6 soap_new_std__vectorTemplateOfPointerTons2__MProductOffer(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__vectorTemplateOfPointerTons2__MProductOffer(struct soap*, std::vector<ns2__MProductOffer * >*);
SOAP_FMAC3 std::vector<ns2__MProductOffer * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerTons2__MProductOffer(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons2__MProductOffer(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons2__MProduct
#define SOAP_TYPE_std__vectorTemplateOfPointerTons2__MProduct (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons2__MProduct(struct soap*, std::vector<ns2__MProduct * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons2__MProduct(struct soap*, const std::vector<ns2__MProduct * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons2__MProduct(struct soap*, const char*, int, const std::vector<ns2__MProduct * >*, const char*);
SOAP_FMAC3 std::vector<ns2__MProduct * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons2__MProduct(struct soap*, const char*, std::vector<ns2__MProduct * >*, const char*);
SOAP_FMAC5 std::vector<ns2__MProduct * > * SOAP_FMAC6 soap_new_std__vectorTemplateOfPointerTons2__MProduct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__vectorTemplateOfPointerTons2__MProduct(struct soap*, std::vector<ns2__MProduct * >*);
SOAP_FMAC3 std::vector<ns2__MProduct * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerTons2__MProduct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons2__MProduct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons2__MBusinessCard
#define SOAP_TYPE_std__vectorTemplateOfPointerTons2__MBusinessCard (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons2__MBusinessCard(struct soap*, std::vector<ns2__MBusinessCard * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons2__MBusinessCard(struct soap*, const std::vector<ns2__MBusinessCard * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons2__MBusinessCard(struct soap*, const char*, int, const std::vector<ns2__MBusinessCard * >*, const char*);
SOAP_FMAC3 std::vector<ns2__MBusinessCard * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons2__MBusinessCard(struct soap*, const char*, std::vector<ns2__MBusinessCard * >*, const char*);
SOAP_FMAC5 std::vector<ns2__MBusinessCard * > * SOAP_FMAC6 soap_new_std__vectorTemplateOfPointerTons2__MBusinessCard(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__vectorTemplateOfPointerTons2__MBusinessCard(struct soap*, std::vector<ns2__MBusinessCard * >*);
SOAP_FMAC3 std::vector<ns2__MBusinessCard * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerTons2__MBusinessCard(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons2__MBusinessCard(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons2__MCategory
#define SOAP_TYPE_std__vectorTemplateOfPointerTons2__MCategory (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons2__MCategory(struct soap*, std::vector<ns2__MCategory * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons2__MCategory(struct soap*, const std::vector<ns2__MCategory * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons2__MCategory(struct soap*, const char*, int, const std::vector<ns2__MCategory * >*, const char*);
SOAP_FMAC3 std::vector<ns2__MCategory * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons2__MCategory(struct soap*, const char*, std::vector<ns2__MCategory * >*, const char*);
SOAP_FMAC5 std::vector<ns2__MCategory * > * SOAP_FMAC6 soap_new_std__vectorTemplateOfPointerTons2__MCategory(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__vectorTemplateOfPointerTons2__MCategory(struct soap*, std::vector<ns2__MCategory * >*);
SOAP_FMAC3 std::vector<ns2__MCategory * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerTons2__MCategory(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons2__MCategory(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* End of soapH.h */
