/* soapServer.cpp
   Generated by gSOAP 2.7.11 from ../../IMobile.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.7.11 2008-08-13 08:19:14 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else 
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || soap_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getProductDetails"))
		return soap_serve___ns3__getProductDetails(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getCategoryList"))
		return soap_serve___ns3__getCategoryList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getBusinessList"))
		return soap_serve___ns3__getBusinessList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getProductList"))
		return soap_serve___ns3__getProductList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getBusinessDetails"))
		return soap_serve___ns3__getBusinessDetails(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getProductDetails"))
		return soap_serve___ns4__getProductDetails(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getCategoryList"))
		return soap_serve___ns4__getCategoryList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getBusinessList"))
		return soap_serve___ns4__getBusinessList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getProductList"))
		return soap_serve___ns4__getProductList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getBusinessDetails"))
		return soap_serve___ns4__getBusinessDetails(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns3__getProductDetails(struct soap *soap)
{	struct __ns3__getProductDetails soap_tmp___ns3__getProductDetails;
	_ns1__getProductDetailsResponse ns1__getProductDetailsResponse;
	ns1__getProductDetailsResponse.soap_default(soap);
	soap_default___ns3__getProductDetails(soap, &soap_tmp___ns3__getProductDetails);
	soap->encodingStyle = NULL;
	if (!soap_get___ns3__getProductDetails(soap, &soap_tmp___ns3__getProductDetails, "-ns3:getProductDetails", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns3__getProductDetails(soap, soap_tmp___ns3__getProductDetails.ns1__getProductDetails, &ns1__getProductDetailsResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__getProductDetailsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__getProductDetailsResponse.soap_put(soap, "ns1:getProductDetailsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__getProductDetailsResponse.soap_put(soap, "ns1:getProductDetailsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns3__getCategoryList(struct soap *soap)
{	struct __ns3__getCategoryList soap_tmp___ns3__getCategoryList;
	_ns1__getCategoryListResponse ns1__getCategoryListResponse;
	ns1__getCategoryListResponse.soap_default(soap);
	soap_default___ns3__getCategoryList(soap, &soap_tmp___ns3__getCategoryList);
	soap->encodingStyle = NULL;
	if (!soap_get___ns3__getCategoryList(soap, &soap_tmp___ns3__getCategoryList, "-ns3:getCategoryList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns3__getCategoryList(soap, soap_tmp___ns3__getCategoryList.ns1__getCategoryList, &ns1__getCategoryListResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__getCategoryListResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__getCategoryListResponse.soap_put(soap, "ns1:getCategoryListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__getCategoryListResponse.soap_put(soap, "ns1:getCategoryListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns3__getBusinessList(struct soap *soap)
{	struct __ns3__getBusinessList soap_tmp___ns3__getBusinessList;
	_ns1__getBusinessListResponse ns1__getBusinessListResponse;
	ns1__getBusinessListResponse.soap_default(soap);
	soap_default___ns3__getBusinessList(soap, &soap_tmp___ns3__getBusinessList);
	soap->encodingStyle = NULL;
	if (!soap_get___ns3__getBusinessList(soap, &soap_tmp___ns3__getBusinessList, "-ns3:getBusinessList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns3__getBusinessList(soap, soap_tmp___ns3__getBusinessList.ns1__getBusinessList, &ns1__getBusinessListResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__getBusinessListResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__getBusinessListResponse.soap_put(soap, "ns1:getBusinessListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__getBusinessListResponse.soap_put(soap, "ns1:getBusinessListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns3__getProductList(struct soap *soap)
{	struct __ns3__getProductList soap_tmp___ns3__getProductList;
	_ns1__getProductListResponse ns1__getProductListResponse;
	ns1__getProductListResponse.soap_default(soap);
	soap_default___ns3__getProductList(soap, &soap_tmp___ns3__getProductList);
	soap->encodingStyle = NULL;
	if (!soap_get___ns3__getProductList(soap, &soap_tmp___ns3__getProductList, "-ns3:getProductList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns3__getProductList(soap, soap_tmp___ns3__getProductList.ns1__getProductList, &ns1__getProductListResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__getProductListResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__getProductListResponse.soap_put(soap, "ns1:getProductListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__getProductListResponse.soap_put(soap, "ns1:getProductListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns3__getBusinessDetails(struct soap *soap)
{	struct __ns3__getBusinessDetails soap_tmp___ns3__getBusinessDetails;
	_ns1__getBusinessDetailsResponse ns1__getBusinessDetailsResponse;
	ns1__getBusinessDetailsResponse.soap_default(soap);
	soap_default___ns3__getBusinessDetails(soap, &soap_tmp___ns3__getBusinessDetails);
	soap->encodingStyle = NULL;
	if (!soap_get___ns3__getBusinessDetails(soap, &soap_tmp___ns3__getBusinessDetails, "-ns3:getBusinessDetails", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns3__getBusinessDetails(soap, soap_tmp___ns3__getBusinessDetails.ns1__getBusinessDetails, &ns1__getBusinessDetailsResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__getBusinessDetailsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__getBusinessDetailsResponse.soap_put(soap, "ns1:getBusinessDetailsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__getBusinessDetailsResponse.soap_put(soap, "ns1:getBusinessDetailsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns4__getProductDetails(struct soap *soap)
{	struct __ns4__getProductDetails soap_tmp___ns4__getProductDetails;
	_ns1__getProductDetailsResponse ns1__getProductDetailsResponse;
	ns1__getProductDetailsResponse.soap_default(soap);
	soap_default___ns4__getProductDetails(soap, &soap_tmp___ns4__getProductDetails);
	soap->encodingStyle = NULL;
	if (!soap_get___ns4__getProductDetails(soap, &soap_tmp___ns4__getProductDetails, "-ns4:getProductDetails", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns4__getProductDetails(soap, soap_tmp___ns4__getProductDetails.ns1__getProductDetails, &ns1__getProductDetailsResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__getProductDetailsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__getProductDetailsResponse.soap_put(soap, "ns1:getProductDetailsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__getProductDetailsResponse.soap_put(soap, "ns1:getProductDetailsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns4__getCategoryList(struct soap *soap)
{	struct __ns4__getCategoryList soap_tmp___ns4__getCategoryList;
	_ns1__getCategoryListResponse ns1__getCategoryListResponse;
	ns1__getCategoryListResponse.soap_default(soap);
	soap_default___ns4__getCategoryList(soap, &soap_tmp___ns4__getCategoryList);
	soap->encodingStyle = NULL;
	if (!soap_get___ns4__getCategoryList(soap, &soap_tmp___ns4__getCategoryList, "-ns4:getCategoryList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns4__getCategoryList(soap, soap_tmp___ns4__getCategoryList.ns1__getCategoryList, &ns1__getCategoryListResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__getCategoryListResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__getCategoryListResponse.soap_put(soap, "ns1:getCategoryListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__getCategoryListResponse.soap_put(soap, "ns1:getCategoryListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns4__getBusinessList(struct soap *soap)
{	struct __ns4__getBusinessList soap_tmp___ns4__getBusinessList;
	_ns1__getBusinessListResponse ns1__getBusinessListResponse;
	ns1__getBusinessListResponse.soap_default(soap);
	soap_default___ns4__getBusinessList(soap, &soap_tmp___ns4__getBusinessList);
	soap->encodingStyle = NULL;
	if (!soap_get___ns4__getBusinessList(soap, &soap_tmp___ns4__getBusinessList, "-ns4:getBusinessList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns4__getBusinessList(soap, soap_tmp___ns4__getBusinessList.ns1__getBusinessList, &ns1__getBusinessListResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__getBusinessListResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__getBusinessListResponse.soap_put(soap, "ns1:getBusinessListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__getBusinessListResponse.soap_put(soap, "ns1:getBusinessListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns4__getProductList(struct soap *soap)
{	struct __ns4__getProductList soap_tmp___ns4__getProductList;
	_ns1__getProductListResponse ns1__getProductListResponse;
	ns1__getProductListResponse.soap_default(soap);
	soap_default___ns4__getProductList(soap, &soap_tmp___ns4__getProductList);
	soap->encodingStyle = NULL;
	if (!soap_get___ns4__getProductList(soap, &soap_tmp___ns4__getProductList, "-ns4:getProductList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns4__getProductList(soap, soap_tmp___ns4__getProductList.ns1__getProductList, &ns1__getProductListResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__getProductListResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__getProductListResponse.soap_put(soap, "ns1:getProductListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__getProductListResponse.soap_put(soap, "ns1:getProductListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns4__getBusinessDetails(struct soap *soap)
{	struct __ns4__getBusinessDetails soap_tmp___ns4__getBusinessDetails;
	_ns1__getBusinessDetailsResponse ns1__getBusinessDetailsResponse;
	ns1__getBusinessDetailsResponse.soap_default(soap);
	soap_default___ns4__getBusinessDetails(soap, &soap_tmp___ns4__getBusinessDetails);
	soap->encodingStyle = NULL;
	if (!soap_get___ns4__getBusinessDetails(soap, &soap_tmp___ns4__getBusinessDetails, "-ns4:getBusinessDetails", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns4__getBusinessDetails(soap, soap_tmp___ns4__getBusinessDetails.ns1__getBusinessDetails, &ns1__getBusinessDetailsResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__getBusinessDetailsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__getBusinessDetailsResponse.soap_put(soap, "ns1:getBusinessDetailsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__getBusinessDetailsResponse.soap_put(soap, "ns1:getBusinessDetailsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

/* End of soapServer.cpp */
