/* soapIMobileSoap12BindingObject.h
   Generated by gSOAP 2.7.11 from ../../IMobile.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapIMobileSoap12BindingObject_H
#define soapIMobileSoap12BindingObject_H
#include "soapH.h"

/******************************************************************************\
 *                                                                            *
 * Service Object                                                             *
 *                                                                            *
\******************************************************************************/

class IMobileSoap12BindingService : public soap
{    public:
	IMobileSoap12BindingService()
	{ static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "http://mobile.kenlo.com/xsd", NULL, NULL},
	{"ns3", "http://mobile.kenlo.com/IMobileSoap11Binding", NULL, NULL},
	{"ns1", "http://mobile.kenlo.com", NULL, NULL},
	{"ns4", "http://mobile.kenlo.com/IMobileSoap12Binding", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	if (!this->namespaces) this->namespaces = namespaces; };
	virtual ~IMobileSoap12BindingService() { };
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog) { return soap_bind(this, host, port, backlog); };
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept() { return soap_accept(this); };
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve() { return soap_serve(this); };
};

/******************************************************************************\
 *                                                                            *
 * Service Operations (you should define these globally)                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __ns3__getProductDetails(struct soap*, _ns1__getProductDetails *ns1__getProductDetails, _ns1__getProductDetailsResponse *ns1__getProductDetailsResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__getCategoryList(struct soap*, _ns1__getCategoryList *ns1__getCategoryList, _ns1__getCategoryListResponse *ns1__getCategoryListResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__getBusinessList(struct soap*, _ns1__getBusinessList *ns1__getBusinessList, _ns1__getBusinessListResponse *ns1__getBusinessListResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__getProductList(struct soap*, _ns1__getProductList *ns1__getProductList, _ns1__getProductListResponse *ns1__getProductListResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__getBusinessDetails(struct soap*, _ns1__getBusinessDetails *ns1__getBusinessDetails, _ns1__getBusinessDetailsResponse *ns1__getBusinessDetailsResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__getProductDetails(struct soap*, _ns1__getProductDetails *ns1__getProductDetails, _ns1__getProductDetailsResponse *ns1__getProductDetailsResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__getCategoryList(struct soap*, _ns1__getCategoryList *ns1__getCategoryList, _ns1__getCategoryListResponse *ns1__getCategoryListResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__getBusinessList(struct soap*, _ns1__getBusinessList *ns1__getBusinessList, _ns1__getBusinessListResponse *ns1__getBusinessListResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__getProductList(struct soap*, _ns1__getProductList *ns1__getProductList, _ns1__getProductListResponse *ns1__getProductListResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__getBusinessDetails(struct soap*, _ns1__getBusinessDetails *ns1__getBusinessDetails, _ns1__getBusinessDetailsResponse *ns1__getBusinessDetailsResponse);

#endif
